import test from 'node:test';import assert from 'node:assert/strict';
import {World} from '../src/coop/model.js';
import {startBonusEvent,tryBonusEvent,BONUS_RULES} from '../src/coop/bonus-events.js';
const arena=()=>{const w=new World(183);w.reset(['warrior','mage'],2);w.enemies=[];w.obstacles=[];w.pressure=null;w.clears=4;w.heroes.forEach((h,i)=>{h.x=i*150;h.y=0;});return w;};
test('a real projectile drops one coin per target, repeated ticks cannot farm a pierced target',()=>{
 const w=arena();startBonusEvent(w,'gold');const h=w.heroes[1],e=w.enemies[0];w.enemies=[e];h.x=h.y=0;e.x=100;e.y=0;
 w.shoot(h,{x:1,y:0},'pierce',45,650,'skill');w.updateProjectiles(.2);w.updateProjectiles(.2);assert.equal(w.bonusEvent.goldDropped,1);assert.equal(e.hp,1);
 w.obstacles=[{x:60,y:0,r:25}];w.shoot(h,{x:1,y:0},'arrow',24);w.updateProjectiles(.3);assert.equal(w.bonusEvent.goldDropped,1,'blocked shots give no gold');
});
test('event creatures stay bounded and finite; living cap and guaranteed drops persist over a full timer',()=>{
 const w=arena();startBonusEvent(w,'xp');w.heroes.forEach(h=>h.attackCd=1000);
 for(let i=0;i<17*60;i++){w.advance(1/60);w.events=[];assert.ok(w.enemies.length<=120);}
 assert.ok(w.enemies.every(e=>Number.isFinite(e.x+e.y+e.stride)&&Math.abs(e.x)<=w.bonusEvent.bounds.x&&Math.abs(e.y)<=w.bonusEvent.bounds.y));
 assert.ok(w.heroes.every(h=>h.hp===h.maxHp));
});
test('rare roll is checked only at eligible wave boundaries and respects cooldown',()=>{const w=arena();w.random=()=>.8;assert.equal(tryBonusEvent(w),false);w.random=()=>.02;assert.equal(tryBonusEvent(w),true);assert.equal(w.bonusEvent.kind,'xp');assert.equal(tryBonusEvent(w),false);w.bonusEvent=null;w.clears=6;assert.equal(tryBonusEvent(w),false);w.clears=7;w.random=()=>.07;assert.equal(tryBonusEvent(w),true);assert.equal(w.bonusEvent.kind,'gold');});
test('experience swarm keeps replenishing, never attacks or contacts, and always drops XP',()=>{const w=arena();startBonusEvent(w,'xp');const count=w.enemies.length,h=w.heroes[0],hp=h.hp,e=w.enemies[0];e.x=h.x;e.y=h.y;w.resolveBodies();assert.equal(h.hp,hp);w.random=()=>.999;w.damageEnemy(e,999,h);assert.equal(w.pickups.filter(p=>p.type==='xp').reduce((n,p)=>n+p.value,0),1);assert.equal(w.pickups.some(p=>p.type==='gold'||p.type==='potion'),false);w.advance(.5);assert.ok(w.bonusEvent.spawned>count);assert.ok(w.enemies.length<=BONUS_RULES.xp.cap+20*w.humanCount);assert.ok(w.enemies.every(e=>!e.action));assert.equal(h.hp,hp);});
test('coin creatures survive every attack type, drop real coins per hit, and only flee',()=>{const w=arena();startBonusEvent(w,'gold');const e=w.enemies[0],h=w.heroes[0],hp=e.hp;for(const source of ['attack','skill','proc','dot'])w.damageEnemy(e,999999,h,999,source);assert.equal(e.hp,hp);assert.equal(e.defeated,undefined);assert.equal(w.kills,0);assert.equal(w.pickups.reduce((n,p)=>n+p.value,0),4);assert.equal(h.gold,0);e.x=h.x+20;e.y=h.y;const x=e.x;w.updateEnemy(e,.2);assert.ok(e.x>x);assert.equal(e.action,null);w.damageEnemy(e,0,h);assert.equal(w.pickups.reduce((n,p)=>n+p.value,0),4);});
test('timers pause in upgrade/pause, finishing does not increment clear or grant another skill reward',()=>{const w=arena();w.wave=1;startBonusEvent(w,'gold');const remaining=w.bonusEvent.remaining;w.pause();w.advance(5);assert.equal(w.bonusEvent.remaining,remaining);w.resume();w.xp=w.xpNext;w.advance(.01);assert.equal(w.mode,'upgrade');const paused=w.bonusEvent.remaining;w.advance(10);assert.equal(w.bonusEvent.remaining,paused);w.confirm(0);w.confirm(1);assert.equal(w.mode,'play');w.bonusEvent.remaining=.001;w.advance(.01);assert.equal(w.bonusEvent.phase,'collect');assert.equal(w.enemies.length,0);w.bonusEvent.remaining=.001;w.advance(.01);assert.equal(w.bonusEvent,null);assert.equal(w.wave,2);assert.equal(w.clears,4);assert.equal(w.mode,'play');});
test('timeout flees without death loot; personal ground coins persist; fifth room still enters shop',()=>{const w=arena();w.room=5;w.wave=2;startBonusEvent(w,'gold');const e=w.enemies[0];w.damageEnemy(e,1,w.heroes[0]);w.bonusEvent.remaining=0;w.advance(.01);assert.equal(w.enemies.length,0);assert.equal(w.pickups.filter(p=>p.type==='gold').reduce((n,p)=>n+p.value,0),1);assert.equal(w.kills,0);w.bonusEvent.remaining=0;w.advance(.01);assert.equal(w.mode,'shop');assert.equal(w.clears,4);assert.equal(w.shop.stalls.length,2);});
test('event eligibility excludes bosses and starter clear; normal waves cannot spawn reward enemies',()=>{const w=arena();w.random=()=>0;w.bossRoom=true;assert.equal(tryBonusEvent(w),false);w.bossRoom=false;w.clears=1;assert.equal(tryBonusEvent(w),false);w.spawnWave();assert.ok(w.enemies.every(e=>!e.bonusKind));});
