import test from 'node:test';
import assert from 'node:assert/strict';
import {ACTIVE,FORMS,applyReward,attributePool,evolutionStatus,formInfo,rollSkills,skillName,skillPool,rollReshape,replacementImpacts} from '../src/coop/builds.js';
import {ROUTES,BRANCHES} from '../src/coop/progression-data.js';
const hero=(role='warrior')=>({role,skills:[0,0],forms:[null,null],evolved:[false,false],runes:[null,null],passives:{},core:null,power:1,skillPower:1,dotPower:1,shieldPower:1,hp:100,maxHp:100,speedBonus:1,haste:1,crit:0,critDamage:1.5,evasion:0,armor:0,cooldown:0,rangeBonus:1,recovery:1,cd:[0,0]});
const rng=(seed=17)=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const has=(h,key)=>skillPool(h).some(o=>o.key===key);

test('first active assurance occupies the general slot and can be declined',()=>{for(const role of Object.keys(ACTIVE)){const h=hero(role),offers=rollSkills(h,rng(),{clears:1});assert.deepEqual(h.skills,[0,0]);assert.equal(offers[0].kind,'active');assert.equal(offers[0].offerReason,'基础主动保障');assert.ok(!offers.some(o=>o.kind==='core'||o.kind==='form'));assert.ok(!skillPool(h).some(o=>o.kind==='form'));for(const clear of [4,7,10])assert.equal(rollSkills(h,rng(clear),{clears:clear})[0].kind,'active');}});

test('all six forms preserve current level and leave base upgrade available',()=>{assert.equal(Object.keys(FORMS).length,6);for(const [key,f] of Object.entries(FORMS)){const h=hero(f.role);applyReward(h,`active:${f.slot}`);assert.ok(has(h,`active:${f.slot}`));assert.ok(has(h,`form:${f.slot}:${key}`));applyReward(h,`form:${f.slot}:${key}`);assert.equal(h.skills[f.slot],1);assert.equal(formInfo(h,f.slot),f);assert.equal(skillName(h,f.slot),f.title);assert.ok(!skillPool(h).some(o=>o.kind==='form'&&o.slot===f.slot));}});

test('invalid or already chosen forms cannot mutate a hero',()=>{const h=hero();h.skills=[2,2];for(const key of ['form:0:icelance','form:1:aegis','form:2:aegis','form:0:missing'])assert.equal(applyReward(h,key).ok,false);assert.deepEqual(h.forms,[null,null]);applyReward(h,'form:0:aegis');assert.equal(applyReward(h,'form:0:icelance').ok,false);assert.equal(h.forms[0],'aegis');h.evolved[1]=true;assert.equal(applyReward(h,'form:1:bloodspin').ok,false);assert.equal(applyReward(hero(),'form:0:aegis').ok,false);});

test('each of six routes has two explicit recipes, both require a rank II part',()=>{for(const [key,r] of Object.entries(ROUTES)){assert.ok(r.recipes.length>=2);for(const recipe of r.recipes){const h=hero(r.role);h.core=r.core;h.skills=[3,3];if(r.form)h.forms[r.slot]=r.form;assert.equal(evolutionStatus(h,r.slot).ready,false);h.passives=Object.fromEntries(recipe.map(k=>[k,1]));assert.equal(evolutionStatus(h,r.slot).ready,false);h.passives[recipe[0]]=2;assert.equal(evolutionStatus(h,r.slot).ready,true,key);const offers=skillPool(h).filter(o=>o.kind==='evolution'&&o.slot===r.slot);assert.equal(offers.length,2);assert.ok(offers.every(o=>o.quality==='rare'&&o.detail.includes('任一路')));assert.equal(applyReward(h,offers[1].key).ok,true);assert.equal(h.evolutionBranches[r.slot],offers[1].branch);assert.equal(applyReward(h,offers[0].key).ok,false);assert.ok(skillName(h,r.slot).includes(BRANCHES[offers[1].branch].title));}}});

test('unrelated tags and one maxed passive do not substitute for a functional recipe',()=>{const h=hero();h.core='bulwark';h.skills=[3,3];h.forms=['aegis',null];h.passives={thorns:3,guard:1,momentum:2,harvest:2};assert.equal(evolutionStatus(h,0).ready,false);});

test('core offers are random from clear three, never fixed on clear two',()=>{let offered=0,missed=0;for(const role of Object.keys(ACTIVE))for(let seed=1;seed<=100;seed++){const h=hero(role);assert.ok(rollSkills(h,rng(seed),{clears:2}).every(o=>o.kind!=='core'));const next=rollSkills(h,rng(seed),{clears:3});assert.equal(next.length,3);assert.equal(new Set(next.map(o=>o.key)).size,3);if(next.some(o=>o.kind==='core'))offered++;else missed++;assert.ok(!['core','form','evolution'].includes(next[0].kind));}assert.ok(offered>0&&missed>0);});

test('source-specific passives require sources and full slots still allow alternative passives',()=>{const h=hero('archer');for(const key of ['ember','blood','echo','guard','arcane','detonate','storage','afterimage','markCashout'])assert.ok(!has(h,`passive:${key}`),key);h.skills[1]=1;for(const key of ['ember','echo','guard','arcane','afterimage'])assert.ok(has(h,`passive:${key}`),key);h.passives.guard=1;assert.ok(has(h,'passive:storage'));h.passives.ember=1;assert.ok(has(h,'passive:detonate'));h.passives.chill=1;h.passives.momentum=1;assert.ok(has(h,'passive:needleMagazine'));});

test('DOT, shield and pickup attributes have honest sources and caps',()=>{const h=hero('mage');assert.ok(!attributePool(h).some(o=>['dot','shield'].includes(o.key)));h.core='pyromancer';assert.ok(attributePool(h).some(o=>o.key==='dot'));h.skills[0]=1;h.passives.guard=1;assert.ok(attributePool(h).some(o=>o.key==='shield'));for(let i=0;i<20;i++)applyReward(h,'pickup');assert.equal(h.pickupRadius,225);assert.ok(!attributePool(h).some(o=>o.key==='pickup'));});

test('rerolls change at least one visible card and preserve general-slot restrictions',()=>{for(let seed=1;seed<=50;seed++){const h=hero('mage');h.skills=[1,1];const random=rng(seed),before=rollSkills(h,random,{clears:12}),after=rollSkills(h,random,{clears:12,previous:before});assert.ok(after.length===3&&after.some(o=>!before.some(p=>p.key===o.key)));assert.ok(!['core','form','evolution','awakening'].includes(after[0].kind));assert.equal(new Set(after.map(o=>o.key)).size,3);}});

test('high rewards require post-boss context and never guarantee a matching evolution',()=>{const h=hero('mage');h.skills=[3,1];h.core='pyromancer';h.passives={ember:2,emberConsume:1};assert.ok(skillPool(h).some(o=>o.kind==='evolution'));let missed=0;for(let seed=1;seed<=100;seed++){const offers=rollSkills(h,rng(seed*7919),{clears:19,highReward:true});assert.equal(offers.length,3);assert.ok(offers.some(o=>o.quality==='rare'));if(!offers.some(o=>o.kind==='evolution'))missed++;}assert.ok(missed>0);});

test('respec is one-time, preserves levels, and clears old resources without silently replacing other passives',()=>{const h=hero();h.skills=[3,2];h.forms=['aegis','bloodspin'];h.evolved=[true,true];h.evolutionBranches=['bastion','roving'];h.core='bulwark';h.passives={guard:2};h.resource=90;h.shadow={life:2};const choice=rollReshape(h,rng(),'form').find(o=>o.slot===0);assert.ok(choice);const result=applyReward(h,choice.key);assert.ok(result.ok&&result.clearOwnedObjects);assert.deepEqual(h.skills,[3,2]);assert.equal(h.forms[0],null);assert.equal(h.evolved[0],false);assert.deepEqual(h.passives,{guard:2});assert.equal(h.resource,0);assert.equal(h.shadow,null);assert.deepEqual(rollReshape(h,rng(),'core'),[]);});

test('replacement preview identifies exactly the passives whose real source disappears',()=>{const h=hero();h.skills=[1,1];h.passives={guard:1,shieldBrood:2,focus:1,momentum:1};assert.deepEqual(replacementImpacts(h,'guard').map(p=>p.key),['shieldBrood']);assert.equal(applyReward(h,'passive:guardRelease',{replaceKey:'guard'}).ok,false);assert.deepEqual(h.passives,{guard:1,shieldBrood:2,focus:1,momentum:1});});