import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/coop/model.js';
import {addFixtureCompanions} from './hero-fixture.mjs';
import {buildProjectileHit,refundCooldown} from '../src/coop/build-combat.js';

function arena(role='warrior'){
 const w=new World(73);w.reset([role,role==='mage'?'archer':'mage'],1);addFixtureCompanions(w,[role,role==='mage'?'archer':'mage','warrior','mage','archer']);w.enemies=[];w.obstacles=[];w.spawnQueue=[];w.pressure=null;w.waveTimer=-100;w.xpNext=1e6;
 for(const h of w.heroes){h.ai=false;h.x=h.id?900:0;h.y=0;h.attackCd=99;}
 return w;
}
function foe(w,x=90,y=0,kind='mushroom'){const e=w.createEnemy(kind,x,y);e.hp=e.maxHp=1000;e.cd=99;w.enemies.push(e);return e;}

test('absorbed damage only stores charge when the independent storage component is owned',()=>{const w=arena(),h=w.heroes[0],e=foe(w);h.core='bulwark';h.passives.storage=1;h.shield=40;w.damageHero(h,20,e);assert.equal(h.hp,h.maxHp);assert.equal(h.resource,0);assert.equal(h.storedGuard,6);});
test('burn and bleed scale with source strength and dot power',()=>{const w=arena(),h=w.heroes[0],e=foe(w);h.passives={ember:2,blood:1};h.crit=1;h.skillPower=2;h.dotPower=1.5;w.damageEnemy(e,10,h,0,'skill');assert.equal(e.statuses.find(s=>s.type==='burn').damage,24);assert.equal(e.statuses.find(s=>s.type==='bleed').damage,15);});
test('frost core gives bosses a personal brittle window instead of freezing',()=>{const w=arena('mage'),h=w.heroes[0],e=foe(w,90,0,'thornking');h.core='frostweaver';for(let i=0;i<3;i++)w.damageEnemy(e,1,h);assert.equal(e.freeze,0);assert.ok(e.brittle>0);const before=e.hp;w.damageEnemy(e,10,h);assert.ok(before-e.hp>10);});
test('assist rewards belong to contributors and duplicate death does not pay twice',()=>{const w=arena(),h=w.heroes[0],ally=w.heroes[1],e=foe(w);h.passives={harvest:2,echo:2};h.hp=100;h.cd=[2,2];w.damageEnemy(e,30,h);w.damageEnemy(e,2000,ally);assert.equal(h.hp,106);assert.deepEqual(h.cd,[1.4,1.4]);const kills=w.kills;w.damageEnemy(e,2000,h);assert.equal(w.kills,kills);assert.equal(h.hp,106);});
test('effective damage excludes overkill',()=>{const w=arena(),h=w.heroes[0],e=foe(w);e.hp=7;w.damageEnemy(e,1000,h);assert.equal(h.damageDone,7);});
test('one multi-hit attack event gains resource once, distinct attacks still charge',()=>{const w=arena(),h=w.heroes[0],a=foe(w),b=foe(w,100,20);h.core='berserker';w.damageEnemy(a,1,h,0,'attack',0,null,{eventId:80});w.damageEnemy(b,1,h,0,'attack',0,null,{eventId:80});assert.equal(h.resource,14);w.damageEnemy(a,1,h,0,'attack',0,null,{eventId:81});assert.equal(h.resource,28);});
test('aegis stays in place and blocks only frontal attacks during active guard',()=>{const w=arena(),h=w.heroes[0];h.skills=[2,1];h.forms=['aegis',null];w.request(h,'skill1',{x:1,y:0});w.advance(.2,[{x:1,y:0}]);assert.equal(h.x,0);assert.ok(h.guardUntil>w.time);const e=foe(w),hp=h.hp;w.damageHero(h,30,e);assert.equal(h.hp,hp);h.invuln=0;h.shield=0;e.x=-80;w.damageHero(h,30,e);assert.equal(h.hp,hp-30);});
test('bloodspin damages over time while allowing movement and dodge cancellation',()=>{const w=arena(),h=w.heroes[0],e=foe(w);h.skills=[1,2];h.forms=[null,'bloodspin'];w.request(h,'skill2',{x:1,y:0});w.advance(.22,[{x:0,y:1}]);const first=e.hp;assert.ok(h.y>0);w.advance(.25,[{x:0,y:1}]);assert.ok(e.hp<first);assert.ok(e.statuses.some(s=>s.type==='bleed'));assert.equal(w.request(h,'dodge',{x:1,y:0}),true);});
test('ice lance shatters personal brittle into limited nonrecursive fragments',()=>{const w=arena('mage'),h=w.heroes[0],e=foe(w,140);h.core='frostweaver';h.passives.iceFragments=1;h.skills=[2,1];h.forms=['icelance',null];for(let i=0;i<3;i++)w.damageEnemy(e,1,h);w.request(h,'skill1',{x:1,y:0});w.advance(.35);assert.ok(w.effects.some(f=>f.variant==='shatter'));assert.ok(w.projectiles.filter(p=>p.fragment).length<=3);assert.equal(e.chillBy[h.id].brittleUntil,0);});
test('fire detonation spends only owners remaining burn, teammate burn survives',()=>{const w=arena('mage'),h=w.heroes[0],other=w.heroes[1],e=foe(w,100);h.core='pyromancer';h.passives.emberConsume=1;other.passives.ember=1;w.damageEnemy(e,2,h);w.damageEnemy(e,2,other,0,'skill');const own=e.statuses.find(s=>s.owner===h.id),ally=e.statuses.find(s=>s.owner===other.id),oldOwn=own.damage,oldAlly=ally.damage;w.shoot(h,{x:1,y:0},'fireball',20,390,'skill');w.updateProjectiles(.2);assert.ok(own.damage<oldOwn);assert.equal(ally.damage,oldAlly);assert.ok(w.effects.some(f=>f.variant==='inferno'));});
test('marks are personal and marked shot spends only the shooters marks',()=>{const w=arena('archer'),h=w.heroes[0],e=foe(w,220);h.core='sniper';h.passives.markCashout=1;h.skills=[2,1];h.forms=['markedshot',null];for(let i=0;i<5;i++)w.damageEnemy(e,1,h);e.huntMarks[1]={stacks:4,last:w.time};w.request(h,'skill1',{x:1,y:0});w.advance(.48);assert.equal(e.huntMarks[h.id].stacks,0);assert.equal(e.huntMarks[1].stacks,4);assert.ok(w.effects.some(f=>f.variant==='markburst'));});
test('shadow volley uses a finite separate origin and is removed at wave transition',()=>{const w=arena('archer'),h=w.heroes[0];h.core='ranger';h.skills=[1,2];h.forms=[null,'shadowvolley'];w.request(h,'dodge',{x:1,y:0});const origin=h.shadow.x;w.advance(.35);assert.ok(h.x>origin);h.action=null;w.request(h,'skill2',{x:1,y:0});w.advance(.17);assert.ok(w.projectiles.some(p=>p.visual==='shadow'&&p.x<h.x));assert.ok(w.projectiles.length<=15);w.heroes.slice(1).forEach(p=>p.ai=true);w.beginReward('skill');w.confirm(0);assert.equal(h.shadow,null);});

test('evolved aegis lasts longer but dodge removes the real guard immediately',()=>{const w=arena(),h=w.heroes[0];h.skills=[3,1];h.evolved[0]=true;h.forms=['aegis',null];w.request(h,'skill1',{x:1,y:0});w.advance(.2);assert.equal(h.shield,75);assert.ok(h.guardUntil>1.2);assert.equal(w.effects.filter(f=>f.variant==='aegis').length,0);w.request(h,'dodge',{x:0,y:1});assert.equal(h.guardUntil,0);});
test('bloodspin evolution adds one real moving pulse',()=>{const counts=[];for(const evolved of [false,true]){const w=arena(),h=w.heroes[0];h.skills=[1,3];h.forms=[null,'bloodspin'];h.evolved[1]=evolved;w.request(h,'skill2',{x:1,y:0});const action=h.action;w.advance(1.3,[{x:0,y:1}]);counts.push(action.pulses);assert.ok(h.y>100);}assert.deepEqual(counts,[5,6]);});
test('ice lance evolution emits five nonrecursive fragments that exclude their source target',()=>{const w=arena('mage'),h=w.heroes[0],e=foe(w);h.passives.iceFragments=1;e.chillBy={[h.id]:{brittleUntil:2}};const p=w.shoot(h,{x:1,y:0},'pierce',42,720,'skill');p.visual='icelance';p.evolution=true;buildProjectileHit(w,p,e,h,{x:1,y:0});const shards=w.projectiles.filter(p=>p.fragment);assert.equal(shards.length,5);assert.ok(shards.every(p=>p.source==='proc'&&p.hit.has(e.id)));buildProjectileHit(w,shards[0],e,h,{x:1,y:0});assert.equal(w.projectiles.filter(p=>p.fragment).length,5);});
test('coldfield evolution extends lifetime; recast and down never leave an old field',()=>{const w=arena('mage'),h=w.heroes[0];h.skills=[1,3];h.forms=[null,'coldfield'];h.evolved[1]=true;w.request(h,'skill2',{x:1,y:0});w.advance(.2);assert.equal(w.hazards[0].max,5);assert.equal(w.effects.filter(f=>f.variant==='icefield').length,0);h.action=null;h.cd[1]=0;h.x=300;w.request(h,'skill2',{x:1,y:0});w.advance(.2);assert.equal(w.hazards.length,1);assert.equal(w.hazards[0].x,300);h.down=true;w.hazards[0].timer=.5;w.updateHazards(.01);assert.equal(w.hazards.length,0);});
test('evolved marked shot echoes once even when piercing multiple marked enemies',()=>{const w=arena('archer'),h=w.heroes[0],a=foe(w),b=foe(w,160);h.core='sniper';h.passives.markCashout=1;for(const e of [a,b])e.huntMarks={[h.id]:{stacks:5,last:0}};const p=w.shoot(h,{x:1,y:0},'pierce',58,850,'skill');p.form='markedshot';p.evolution=true;for(const e of [a,b])buildProjectileHit(w,p,e,h,{x:1,y:0});assert.equal(w.delayed.filter(j=>j.type==='markecho').length,1);assert.equal(w.delayed[0].damage,29);});
test('evolved shadow repeats once from the original shadow position',()=>{const w=arena('archer'),h=w.heroes[0];h.skills=[1,3];h.forms=[null,'shadowvolley'];h.evolved[1]=true;h.shadow={x:-120,y:60,life:4};w.request(h,'skill2',{x:1,y:0});w.advance(.18);const jobs=w.delayed.filter(j=>j.type==='fan');assert.equal(jobs.length,1);assert.deepEqual(jobs[0].origin,{x:-120,y:60});assert.equal(jobs[0].factor,.45);});
test('kill cooldown refunds cannot exceed 35 percent of each cast',()=>{const w=arena(),h=w.heroes[0];h.skills=[1,1];w.request(h,'skill1',{x:1,y:0});const full=h.cd[0];for(let i=0;i<100;i++)refundCooldown(h,0,1);assert.ok(Math.abs(h.cd[0]-full*.65)<1e-8);});
test('wave confirmation clears effects while attribute selection preserves the current field',()=>{const w=arena('mage'),h=w.heroes[0];h.skills=[1,2];h.forms=[null,'coldfield'];w.request(h,'skill2',{x:1,y:0});w.advance(.2);w.effects.push({type:'build',variant:'inferno',life:3});w.heroes.slice(1).forEach(p=>p.ai=true);w.beginReward('attribute');w.confirm(0);assert.equal(w.hazards.length,1);assert.ok(w.effects.some(f=>f.variant==='inferno'));w.beginReward('skill');w.confirm(0);assert.equal(w.hazards.length,0);assert.ok(!w.effects.some(f=>f.type==='build'));});
