import test from 'node:test';
import assert from 'node:assert/strict';
import {EQUIPMENT_APPEARANCES,EQUIPMENT_AFFIXES,equipmentPrice,validEquipment} from '../src/coop/equipment-data.js';
import {rollEquipment,equipmentMods,equipmentAffixes,applyEquipment,unequipEquipment,withEquipmentBase,onEquipmentAttack,onEquipmentSkill,onEquipmentDodge,onEquipmentHit,onEquipmentHurt,tickEquipment,resetEquipment} from '../src/coop/equipment.js';
import {applyReward} from '../src/coop/builds.js';
import {universalShieldAbsorb,tickUniversal} from '../src/coop/universal-combat.js';
import {universalSources,universalAvailable} from '../src/coop/universal-data.js';

const rng=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
function hero(id=0,role='warrior'){return{id,role,x:0,y:0,hp:80,maxHp:200,power:1,skillPower:1,haste:1,crit:0,armor:0,cooldown:0,speedBonus:1,pickupRadius:75,shield:0,shieldPower:1,down:false,lastMove:{x:1,y:0},skills:[1,0],passives:{},forms:[null,null],evolved:[false,false],cd:[0,0],equipment:{weapon:null,armor:null},damageDone:0};}
function item(role='warrior',slot='weapon',key=null,uid='a'){const i=rollEquipment(role,slot,5,()=>0,uid);i.affixes=key?[{key,strength:1}]:[];return i;}
function equip(h,key,uid=key){const i=item(h.role,EQUIPMENT_AFFIXES[key].slot,key,uid);assert.equal(applyEquipment(h,i).ok,true);return i;}
function arena(){const h=hero(),ally=hero(1);ally.x=600;const w={time:0,nextId:10,nextAttackId:1,heroes:[h,ally],enemies:[],equipmentObjects:[],universalObjects:[],pets:[],effects:[],pickups:[],obstacles:[],lineClear:()=>true,hits:[],damageEnemy(e,n,owner,knock,source,crit,dir,ctx){const actual=Math.min(e.hp,n);e.hp-=actual;w.hits.push({id:e.id,owner:owner.id,damage:actual,knock,source,...ctx});},emit(){}};return{w,h,ally};}
function enemy(w,id,x,y=0){const e={id,kind:'goblin',x,y,hp:100,maxHp:100,slow:0,boss:false};w.enemies.push(e);return e;}

test('equipment provides two separate armor and weapon appearances for all three classes',()=>{const keys=[];for(const role of ['warrior','mage','archer'])for(const slot of ['weapon','armor']){assert.equal(EQUIPMENT_APPEARANCES[role][slot].length,2);keys.push(...EQUIPMENT_APPEARANCES[role][slot].map(s=>s.key));}assert.equal(new Set(keys).size,12);assert.equal(Object.keys(EQUIPMENT_AFFIXES).length,6);});
test('seeded equipment rolls reproduce identity, role, appearance, stats, price and affixes',()=>{const a=rng(17),b=rng(17);for(let i=0;i<40;i++)assert.deepEqual(rollEquipment('mage','armor',9,a,i),rollEquipment('mage','armor',9,b,i));assert.throws(()=>rollEquipment('thief','weapon',1,a,1));assert.throws(()=>rollEquipment('mage','weapon',1,undefined,1));});
test('all four rarities have bounded unique real affixes and both visual variants occur',()=>{for(const role of ['warrior','mage','archer'])for(const slot of ['weapon','armor']){const random=rng(1357),ranks=new Set(),visuals=new Set();for(let i=0;i<800;i++){const e=rollEquipment(role,slot,5,random,i);assert.equal(validEquipment(e),true);ranks.add(e.rarity);visuals.add(e.visualKey);assert.equal(e.affixes.length,e.rarity-1);assert.equal(new Set(e.affixes.map(a=>a.key)).size,e.affixes.length);assert.ok(e.affixes.every(a=>EQUIPMENT_AFFIXES[a.key].slot===slot));}assert.equal(ranks.size,4);assert.equal(visuals.size,2);}});
test('room strength grows actual stats and affix magnitude with a bounded endless ceiling',()=>{const early=rollEquipment('warrior','weapon',1,()=>.3,1),late=rollEquipment('warrior','weapon',20,()=>.3,2),cap=rollEquipment('warrior','weapon',60,()=>.3,3),endless=rollEquipment('warrior','weapon',999,()=>.3,4);assert.equal(early.rarity,late.rarity);assert.ok(late.main.value>early.main.value);assert.ok(late.affixes[0].strength>early.affixes[0].strength);assert.equal(cap.main.value,endless.main.value);assert.equal(cap.affixes[0].strength,endless.affixes[0].strength);});
test('prices consume a meaningful share of the first shop budget and selling cannot fund a repurchase',()=>{assert.deepEqual([1,2,3,4].map(r=>equipmentPrice(r,5)),[24,43,72,112]);for(let r=1;r<=4;r++){assert.ok(equipmentPrice(r,10)>equipmentPrice(r,5));const e=rollEquipment('mage','armor',5,()=>[0,.9,.3,.05,0][r],r);assert.ok(e.sellPrice<e.price*.3);}assert.ok(equipmentPrice(1,5)+equipmentPrice(2,5)>48);});
test('atomic equipment replacement retracts old bonuses, changes visual identity and never heals',()=>{const h=hero(),a=item(),b=item('warrior','weapon',null,'b');a.main={stat:'power',value:.2};b.main={stat:'haste',value:.1};assert.equal(applyEquipment(h,a).ok,true);assert.equal(h.power,1.2);assert.equal(h.hp,80);const result=applyEquipment(h,b);assert.equal(result.old.uid,'a');assert.equal(h.power,1);assert.equal(h.haste,1.1);assert.equal(h.equipment.weapon.uid,'b');assert.equal(h.hp,80);});
test('repeated equip and unequip cannot compound power and does not occupy a passive slot',()=>{const h=hero(),a=item();h.passives={harvest:1};a.main={stat:'power',value:.133};for(let i=0;i<100;i++){applyEquipment(h,a);assert.ok(Math.abs(h.power-1.133)<1e-12);unequipEquipment(h,'weapon');assert.ok(Math.abs(h.power-1)<1e-12);}assert.deepEqual(h.passives,{harvest:1});assert.deepEqual(h.skills,[1,0]);});
test('max-health equipment gives room to heal without creating health; removing it only clips excess',()=>{const h=hero(),a=item('warrior','armor');a.main={stat:'maxHp',value:30};applyEquipment(h,a);assert.equal(h.maxHp,230);assert.equal(h.hp,80);h.hp=225;unequipEquipment(h,'armor');assert.equal(h.hp,200);assert.equal(h.maxHp,200);applyEquipment(h,a);assert.equal(h.hp,200);});
test('wrong class and malformed items are rejected without any mutation, external item edits cannot change worn gear',()=>{const h=hero(),before=structuredClone(h);assert.equal(applyEquipment(h,item('mage')).ok,false);assert.deepEqual(h,before);const a=item();a.main.value=NaN;assert.equal(applyEquipment(h,a).ok,false);assert.deepEqual(h,before);const b=item();applyEquipment(h,b);b.main.value=999;b.affixes.push({key:'capacitor',strength:9});assert.notEqual(h.equipment.weapon.main.value,999);assert.equal(h.equipment.weapon.affixes.length,0);});
test('permanent stat training remains after unequipping, including its own cap',()=>{const h=hero(),a=item();h.crit=.61;a.main={stat:'crit',value:.07};applyEquipment(h,a);withEquipmentBase(h,()=>applyReward(h,'crit'));assert.ok(Math.abs(h.crit-.72)<1e-10);unequipEquipment(h,'weapon');assert.ok(Math.abs(h.crit-.65)<1e-10);});
test('health rewards use the real equipped health ceiling and do not lose current HP',()=>{const h=hero(),a=item('warrior','armor');a.main={stat:'maxHp',value:40};applyEquipment(h,a);h.hp=230;withEquipmentBase(h,()=>applyReward(h,'hp'));assert.equal(h.maxHp,270);assert.equal(h.hp,260);withEquipmentBase(h,()=>applyReward(h,'heal'));assert.equal(h.hp,270);unequipEquipment(h,'armor');assert.equal(h.maxHp,230);assert.equal(h.hp,230);});
test('training wrapper restores equipped capped stats even when the wrapped operation throws',()=>{const h=hero(),a=item();a.main={stat:'crit',value:.08};applyEquipment(h,a);assert.throws(()=>withEquipmentBase(h,()=>{throw Error('failed');}));assert.equal(h.crit,.08);});
test('flash reload has a three-second window, two real projectiles, root-event dedup and no passive gifts',()=>{const {w,h}=arena();equip(h,'dodgeLoad');onEquipmentDodge(w,h,{x:1,y:0});onEquipmentAttack(w,h,{eventId:3,dir:{x:0,y:1}});onEquipmentAttack(w,h,{eventId:3,dir:{x:0,y:1}});assert.equal(w.equipmentObjects.length,2);assert.ok(w.equipmentObjects.every(p=>p.dy>.98&&p.owner===0));assert.deepEqual(h.passives,{});w.time=4;onEquipmentDodge(w,h,{x:1,y:0});w.time=8;onEquipmentAttack(w,h,{eventId:4,dir:{x:1,y:0}});assert.equal(w.equipmentObjects.length,2);});
test('every fourth actual basic attack creates one directional projectile with at most three targets',()=>{const {w,h}=arena();equip(h,'piercingEdge');for(let i=0;i<4;i++)onEquipmentAttack(w,h,{eventId:i,dir:{x:1,y:0}});assert.equal(w.equipmentObjects.length,1);for(let i=0;i<4;i++)enemy(w,100+i,80+i*50);tickEquipment(w,.5);assert.equal(w.hits.length,3);assert.equal(w.enemies[3].hp,100);assert.ok(w.hits.every(hit=>hit.source==='proc'&&hit.depth===1));assert.equal(w.equipmentObjects.length,0);});
test('equipment projectile uses swept body contacts and obstacles terminate its path',()=>{const {w,h}=arena();equip(h,'piercingEdge');for(let i=0;i<4;i++)onEquipmentAttack(w,h,{eventId:i,dir:{x:1,y:0}});enemy(w,100,90);enemy(w,101,220);w.obstacles=[{x:155,y:0,r:15}];tickEquipment(w,.8);assert.equal(w.hits.length,1);assert.equal(w.hits[0].id,100);assert.equal(w.equipmentObjects.length,0);});
test('six distinct basic hit events charge one skill pulse; multihits, DOT and proc cannot charge it',()=>{const {w,h}=arena();equip(h,'capacitor');const e=enemy(w,100,80);for(let i=0;i<6;i++){onEquipmentHit(w,e,h,'attack',{eventId:i},1);onEquipmentHit(w,e,h,'attack',{eventId:i},1);onEquipmentHit(w,e,h,'proc',{eventId:100+i,depth:1},2);}assert.equal(h.equipmentState.charge,6);onEquipmentSkill(w,h,{eventId:99});assert.equal(w.hits.length,1);assert.equal(w.hits[0].knock,220);assert.equal(h.equipmentState.charge,0);onEquipmentSkill(w,h,{eventId:99});assert.equal(w.hits.length,1);});
test('capacitor consumes no charge when a skill is absent, overkill and zero damage do not build charges',()=>{const {w,h}=arena();equip(h,'capacitor');const e=enemy(w,100,80);onEquipmentHit(w,e,h,'attack',{eventId:1},0);onEquipmentHit(w,e,h,'skill',{eventId:2},5);onEquipmentHit(w,e,h,'dot',{eventId:3},5);assert.equal(h.equipmentState?.charge,undefined);onEquipmentSkill(w,h,{eventId:4});assert.equal(w.hits.length,0);});
test('casting ward is temporary, throttled, capped and shares FIFO absorption with other temporary shields',()=>{const {w,h}=arena();equip(h,'spellWard');onEquipmentSkill(w,h,{eventId:1});assert.equal(h.shield,8);onEquipmentSkill(w,h,{eventId:2});assert.equal(h.shield,8);h.shield+=20;h.shield-=5;universalShieldAbsorb(w,h,5);assert.equal(h.universal.shields[0].amount,3);w.time=3.1;tickUniversal(w,.1);assert.equal(h.shield,20);});
test('changing ward equipment removes only its unspent shield and preserves unrelated shields',()=>{const {w,h}=arena();equip(h,'spellWard');onEquipmentSkill(w,h,{eventId:1});h.shield+=20;h.universal.shields.push({amount:4,until:10});h.shield+=4;applyEquipment(h,item('warrior','armor',null,'plain'));assert.equal(h.shield,24);assert.equal(h.universal.shields.length,1);assert.equal(h.universal.shields[0].amount,4);});
test('worn casting ward is a real shield source only with an active; unequipping disables shield dependents',()=>{const h=hero();h.skills=[0,0];equip(h,'spellWard');assert.equal(universalSources(h).shield,false);assert.equal(universalAvailable(h,'shieldBrood'),false);h.skills=[1,0];assert.equal(universalSources(h).shield,true);assert.equal(universalAvailable(h,'shieldBrood'),true);h.passives.shieldBrood=1;applyEquipment(h,item('warrior','armor',null,'plain'));assert.equal(universalSources(h).shield,false);assert.equal(universalAvailable(h,'shieldBrood'),false);});
test('dodge snare has one owner-bounded field, slowing nearby enemies rather than dealing generic bonus damage',()=>{const {w,h}=arena();equip(h,'trailSnare');const e=enemy(w,100,20);onEquipmentDodge(w,h,{x:1,y:0});tickEquipment(w,.1);assert.ok(e.slow>0);assert.equal(e.hp,100);onEquipmentDodge(w,h,{x:1,y:0});assert.equal(w.equipmentObjects.length,1);w.time=6;h.x=200;onEquipmentDodge(w,h,{x:1,y:0});tickEquipment(w,.1);assert.equal(w.equipmentObjects.length,1);assert.equal(w.equipmentObjects[0].x,200);});
test('actual hurt pulls only shared XP and gold without credit, healing, potion movement or wall crossing',()=>{const {w,h}=arena();equip(h,'panicMagnet');w.pickups=[{id:1,type:'xp',x:160,y:0,value:10},{id:2,type:'gold',x:170,y:0,value:2},{id:3,type:'potion',x:150,y:0},{id:4,type:'amber',owner:1,x:150,y:0},{id:5,type:'xp',x:150,y:30}];w.lineClear=(a,b)=>b.id!==5;onEquipmentHurt(w,h,0);assert.equal(w.pickups[0].x,160);onEquipmentHurt(w,h,10);assert.equal(w.pickups[0].x,70);assert.equal(w.pickups[1].x,80);assert.equal(w.pickups[2].x,150);assert.equal(w.pickups[3].x,150);assert.equal(w.pickups[4].x,150);assert.equal(h.hp,80);assert.equal(w.xp,undefined);onEquipmentHurt(w,h,10);assert.equal(w.pickups[0].x,70);});
test('owner reset preserves teammate objects, gear and permanent training while deleting owned effects',()=>{const {w,h,ally}=arena();equip(h,'trailSnare');equip(ally,'trailSnare','ally');onEquipmentDodge(w,h,{x:1,y:0});onEquipmentDodge(w,ally,{x:1,y:0});resetEquipment(w,0);assert.equal(w.equipmentObjects.length,1);assert.equal(w.equipmentObjects[0].owner,1);assert.ok(w.effects.every(e=>e.owner!==0));assert.ok(h.equipment.armor);assert.ok(ally.equipment.armor);});
test('downed or replaced-source equipment cannot leave armed projectiles and fields behind',()=>{const {w,h}=arena();equip(h,'trailSnare');onEquipmentDodge(w,h,{x:1,y:0});applyEquipment(h,item('warrior','armor',null,'other'));tickEquipment(w,.01);assert.equal(w.equipmentObjects.length,0);equip(h,'dodgeLoad');onEquipmentDodge(w,h,{x:1,y:0});onEquipmentAttack(w,h,{eventId:1,dir:{x:1,y:0}});h.down=true;tickEquipment(w,.01);assert.equal(w.equipmentObjects.length,0);assert.deepEqual(h.equipmentState,{});});
test('expiry and per-owner cap bound equipment effects even when an enemy is never hit',()=>{const {w,h}=arena();equip(h,'dodgeLoad');for(let i=0;i<50;i++){w.time=i*4;onEquipmentDodge(w,h,{x:1,y:0});onEquipmentAttack(w,h,{eventId:i,dir:{x:1,y:0}});}assert.equal(w.equipmentObjects.length,12);tickEquipment(w,1);assert.equal(w.equipmentObjects.length,0);});
