import test from 'node:test';
import assert from 'node:assert/strict';
import {World,MAP} from '../src/coop/model.js';
import {MOSSBELL_DEF,MOSSBELL_SIZE,MOSSBELL_BODY_RADIUS,MOSSBELL_SWEEP_RADIUS,MOSSBELL_LEAP_RADIUS,startMossbellSkill,updateMossbell,warningContains} from '../src/coop/mossbell.js';
import {updateBossWarnings} from '../src/coop/boss.js';
import {bossPose} from '../src/coop/adventure-art.js';
import {segmentCircle} from '../src/coop/collision.js';
function fixture(roles=['warrior']){const w=new World(17);w.reset(roles,roles.length);w.enemies=[];w.obstacles=[];w.pressure=null;w.room=10;w.wave=1;w.spawnWave();const b=w.enemies[0],h=w.heroes[0];b.x=0;b.y=0;b.cd=999;h.x=300;h.y=0;h.armor=0;h.evasion=0;h.attackCd=999;w.xpNext=1e9;return{w,b,h};}
test('boss faces the locked target on both sides, including during cooldown turns',()=>{const {w,b,h}=fixture();h.x=200;startMossbellSkill(w,b,'sweep');assert.equal(b.face,0);h.x=-200;assert.equal(b.face,0);startMossbellSkill(w,b,'sweep');assert.equal(b.face,4);});
test('leap travels continuously and reaches the exact previewed, obstacle-safe landing',()=>{const {w,b,h}=fixture();w.obstacles=[{x:300,y:0,r:80}];startMossbellSkill(w,b,'leap');const a=b.action,z=w.bossWarnings[0];assert.ok(Math.hypot(z.x-300,z.y)>=80+MOSSBELL_BODY_RADIUS-1e-6);updateMossbell(w,b,a.windup*.7);assert.ok(b.x>0&&b.x<a.x);assert.ok(bossPose(b,w.time).offset<0);updateMossbell(w,b,a.windup*.3+.001);assert.ok(Math.hypot(b.x-z.x,b.y-z.y)<.01);});
test('airborne boss cannot inflict ground contact before the visible landing',()=>{const {w,b,h}=fixture();startMossbellSkill(w,b,'leap');updateMossbell(w,b,.9);h.x=b.x;h.y=b.y;h.invuln=0;const hp=h.hp;w.resolveBodies();assert.equal(h.hp,hp);});
test('boss body separates a grounded hero instead of trapping them in contact ticks',()=>{const {w,b,h}=fixture();h.x=40;h.y=0;w.resolveBodies();assert.ok(Math.hypot(h.x-b.x,h.y-b.y)>=MOSSBELL_BODY_RADIUS+17-.001);});
test('slow affects boss pursuit without freezing its attack timer',()=>{const normal=fixture(),slow=fixture();slow.b.slow=2;updateMossbell(normal.w,normal.b,.1);updateMossbell(slow.w,slow.b,.1);assert.ok(slow.b.x<normal.b.x*.8);startMossbellSkill(slow.w,slow.b,'roots');updateMossbell(slow.w,slow.b,.2);assert.equal(slow.b.action.t,.2);});
test('distant targets receive a ranged attack instead of an empty sweep',()=>{const {w,b,h}=fixture();b.cd=0;h.x=400;updateMossbell(w,b,.01);assert.notEqual(b.action.kind,'sweep');assert.ok(w.bossWarnings.some(a=>warningContains(a,h)));});
for(const skill of ['sweep','roots','leap','ultimate'])test(`${skill}: release VFX preserves the exact collision geometry, including safe gaps`,()=>{const {w,b}=fixture();startMossbellSkill(w,b,skill);const z={...w.bossWarnings[0]};updateBossWarnings(w,z.windup+.001);const fx=w.effects.find(e=>e.type==='boss-release');assert.ok(fx);for(const key of ['shape','x','y','r','inner','gap','gapWidth','angle','arc','to'])assert.deepEqual(fx[key],z[key],key);assert.equal(w.events.filter(e=>e.type==='bossImpact').length,1);});
test('no damage during windup, exactly one hit per warning, immunity prevents stacked damage',()=>{const {w,b,h}=fixture();h.x=100;const hp=h.hp;startMossbellSkill(w,b,'sweep');updateBossWarnings(w,1.09);assert.equal(h.hp,hp);updateBossWarnings(w,.02);assert.ok(h.hp<hp);const after=h.hp;h.invuln=0;updateBossWarnings(w,.05);assert.equal(h.hp,after);h.invuln=.2;startMossbellSkill(w,b,'sweep');updateBossWarnings(w,1.11);assert.equal(h.hp,after);});
test('damage follows boss scaling and armor; safe ring gap receives no damage',()=>{const {w,b,h}=fixture();h.x=100;h.armor=.2;startMossbellSkill(w,b,'sweep');const hp=h.hp,damage=b.stats.damage*1.1*.8;updateBossWarnings(w,1.11);assert.ok(Math.abs(hp-h.hp-damage)<1e-6);h.invuln=0;h.x=150;h.y=0;startMossbellSkill(w,b,'ultimate');const safe=h.hp;updateBossWarnings(w,2.21);assert.equal(h.hp,safe);});
test('pausing freezes leap, warning timers and damage',()=>{const {w,b}=fixture();startMossbellSkill(w,b,'leap');w.pause();w.advance(3);assert.equal(b.action.t,0);assert.equal(w.bossWarnings[0].t,0);});
test('feedback toggle does not change attack damage or collision',()=>{const a=fixture(),b=fixture();b.w.options.feedback=false;b.w.options.shake=false;for(const f of [a,b]){f.h.x=100;startMossbellSkill(f.w,f.b,'sweep');updateBossWarnings(f.w,1.11);}assert.equal(a.h.hp,b.h.hp);assert.equal(a.w.bossWarnings[0].hit,b.w.bossWarnings[0].hit);});
test('leap at the hero center has a real impact direction and honors directional guard',()=>{const a=fixture(),b=fixture();for(const f of [a,b])startMossbellSkill(f.w,f.b,'leap');b.h.guardUntil=10;b.h.guardDir={x:-1,y:0};const hp=a.h.hp;for(const f of [a,b])updateBossWarnings(f.w,1.41);assert.ok(Math.abs(hp-b.h.hp-(hp-a.h.hp)*.5)<1e-6);});
test('dodge immunity blocks a released boss attack and its contact in the same tick',()=>{const {w,b,h}=fixture();h.x=40;h.action={type:'dodge',t:.1,duration:.3};h.invuln=.2;startMossbellSkill(w,b,'sweep');const hp=h.hp;updateBossWarnings(w,1.11);w.resolveBodies();assert.equal(h.hp,hp);});
test('high-speed projectile hits boss ground body without tunneling and misses outside radius',()=>{
 for(const [y,hit] of [[0,true],[MOSSBELL_BODY_RADIUS-.25,true],[MOSSBELL_BODY_RADIUS+.25,false]]){const {w,b,h}=fixture();h.crit=0;w.projectiles=[{id:100,owner:0,type:'arrow',source:'attack',eventId:100,x:-200,y,dx:1,dy:0,speed:4000,damage:10,life:2,hit:new Set()}];const hp=b.hp;w.updateProjectiles(.1);assert.equal(b.hp<hp,hit);}
});
test('leap covers its flight in small continuous steps, with no last-frame teleport',()=>{const {w,b}=fixture();startMossbellSkill(w,b,'leap');for(let i=0;i<180;i++){const x=b.x,y=b.y;updateMossbell(w,b,1/120);assert.ok(Math.hypot(b.x-x,b.y-y)<6);}});

test('larger boss silhouette and ground body preserve HP, damage, and full windups',()=>{const {w,b}=fixture();assert.equal(MOSSBELL_SIZE,350);assert.equal(b.stats.size,MOSSBELL_SIZE);assert.equal(b.stats.bodyRadius,MOSSBELL_BODY_RADIUS);assert.equal(b.maxHp,3000);assert.equal(MOSSBELL_DEF.damage,18);for(const [key,windup] of [['sweep',1.1],['roots',1.05],['leap',1.4],['summon',1.3],['ultimate',2.2],['transition',1.4]]){startMossbellSkill(w,b,key);assert.equal(b.action.windup,windup);}});
test('larger weapon and landing use modestly enlarged exact warnings',()=>{const {w,b}=fixture();startMossbellSkill(w,b,'sweep');assert.equal(w.bossWarnings.at(-1).r,MOSSBELL_SWEEP_RADIUS);startMossbellSkill(w,b,'leap');assert.equal(w.bossWarnings.at(-1).r,MOSSBELL_LEAP_RADIUS);});
test('a normal warrior swing connects from outside the enlarged contact body',()=>{const {w,b,h}=fixture();h.x=MOSSBELL_BODY_RADIUS+17+10;h.crit=0;h.action={type:'attack',t:0,windup:.1,duration:.4,fired:false,dir:{x:-1,y:0},eventId:321};const hp=b.hp,heroHp=h.hp;w.advance(.12);assert.ok(b.hp<hp);assert.equal(h.hp,heroHp);});
test('basic shield charge connects with the enlarged boss before body separation blocks its center',()=>{const {w,b,h}=fixture();h.x=170;h.skills=[1,0,0,0];h.crit=0;const hp=b.hp;assert.equal(w.request(h,'skill1',{x:-1,y:0}),true);w.advance(.6);assert.ok(b.hp<hp);assert.ok(b.stagger>0);assert.equal(h.swings,0);});
test('large leap landing respects arena bounds with the full ground radius',()=>{const {w,b,h}=fixture();h.x=MAP.x-17;h.y=MAP.y-17;startMossbellSkill(w,b,'leap');const a=b.action;assert.ok(a.x<=MAP.x-MOSSBELL_BODY_RADIUS);assert.ok(a.y<=MAP.y-MOSSBELL_BODY_RADIUS);updateMossbell(w,b,a.windup);assert.equal(b.x,a.x);assert.equal(b.y,a.y);});
test('ranged skills alternate living partners, while sweep faces the nearby hero',()=>{const {w,b,h}=fixture(['warrior','mage']),other=w.heroes[1];h.x=140;h.y=0;other.x=-350;other.y=0;startMossbellSkill(w,b,'roots');assert.equal(b.action.targetId,other.id);const locked={...b.action};other.x=-450;updateMossbell(w,b,.1);assert.equal(b.action.x,locked.x);assert.equal(b.action.angle,locked.angle);startMossbellSkill(w,b,'leap');assert.equal(b.action.targetId,h.id);startMossbellSkill(w,b,'roots');assert.equal(b.action.targetId,other.id);startMossbellSkill(w,b,'sweep');assert.equal(b.action.targetId,h.id);assert.equal(b.face,0);other.down=true;startMossbellSkill(w,b,'roots');assert.equal(b.action.targetId,h.id);});
test('phase two introduces summons then root lanes before the ordinary rotation',()=>{const {w,b}=fixture();b.hp=b.maxHp*.65;updateMossbell(w,b,.01);assert.equal(b.phase,2);assert.equal(b.action.kind,'transition');updateMossbell(w,b,b.action.duration);b.cd=0;updateMossbell(w,b,.01);assert.equal(b.action.kind,'summon');updateMossbell(w,b,b.action.duration);assert.equal(w.enemies.filter(e=>e.summonedBy===b.id).length,3);b.cd=0;updateMossbell(w,b,.01);assert.equal(b.action.kind,'roots');});
test('phase transition never locks HP or forces skipped phase skills',()=>{const {w,b,h}=fixture();b.hp=b.maxHp*.65;updateMossbell(w,b,.01);assert.equal(b.action.kind,'transition');h.crit=0;w.damageEnemy(b,1e7,h,0,'skill');assert.ok(b.hp<=0);assert.equal(w.bossWarnings.length,0);const fast=fixture();fast.b.hp=fast.b.maxHp*.2;updateMossbell(fast.w,fast.b,.01);assert.equal(fast.b.phase,3);assert.deepEqual(fast.b.phaseOpening,[]);updateMossbell(fast.w,fast.b,fast.b.action.duration);fast.b.cd=0;updateMossbell(fast.w,fast.b,.01);assert.equal(fast.b.action.kind,'ultimate');});
test('ultimate retains a walkable central pocket and four seconds of exposed recovery',()=>{const {w,b}=fixture();b.phase=3;startMossbellSkill(w,b,'ultimate');const a=b.action,inner=w.bossWarnings[0].inner;assert.ok(inner>MOSSBELL_BODY_RADIUS+17+20);assert.ok(w.bossWarnings.every(z=>!warningContains(z,{x:100,y:0})));updateMossbell(w,b,a.windup+1.4);assert.equal(b.staggerUntil-w.time,4);assert.ok(Math.abs(a.duration-a.t-4)<1e-6);assert.ok(w.bossWarnings.every(z=>z.skill==='ultimate'));});
test('delayed melee steering settles within attack range without repeatedly walking into a stationary boss',()=>{const {w,b,h}=fixture();h.x=170;h.y=0;h.skills=[0,0,0,0];const hp=h.hp,queue=[];let held={};for(let frame=0;frame<180;frame++){if(frame%3===0)queue.push({at:w.time+.18,input:w.aiInput(h)});while(queue[0]?.at<=w.time)held=queue.shift().input;w.advance(1/30,[held]);}assert.equal(h.hp,hp);const d=Math.hypot(h.x-b.x,h.y-b.y);assert.ok(d>=(MOSSBELL_BODY_RADIUS+17));assert.ok(d<=145);});
test('cone avoidance routes around the enlarged ground body rather than taking an inward chord',()=>{const {w,b,h}=fixture();h.x=125;h.y=0;h.skills=[0,0,0,0];startMossbellSkill(w,b,'sweep');const input=w.aiInput(h),end={x:h.x+input.x*64,y:h.y+input.y*64};assert.equal(h.aiIntent,'evade');assert.ok(Math.hypot(input.x,input.y)>.5);assert.equal(segmentCircle(h,end,b,MOSSBELL_BODY_RADIUS+17),Infinity);});
