import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/coop/model.js';
import {addFixtureCompanions} from './hero-fixture.mjs';
import {addDot,buildProjectileHit,castShadow,onBuildDodge,releaseBuildEnergy,configureBuildAction,updateBuildAction,tickBuild} from '../src/coop/build-combat.js';
function arena(role='warrior'){
 const w=new World(319);w.reset([role,role==='mage'?'archer':'mage'],1);addFixtureCompanions(w,[role,role==='mage'?'archer':'mage','warrior','mage','archer']);w.enemies=[];w.obstacles=[];w.spawnQueue=[];w.updateSpawns=()=>{};w.xpNext=1e8;w.waveTimer=-100;w.waveDuration=999;
 for(const h of w.heroes){h.ai=false;h.x=h.id?900:0;h.y=0;h.attackCd=99;h.skills=[3,3];h.evolutionBranches=[null,null];}
 const h=w.heroes[0],foe=(x=100,y=0)=>{const e=w.createEnemy('goblin',x,y);e.hp=e.maxHp=1000;e.cd=99;e.freeze=99;w.enemies.push(e);return e;};return{w,h,foe};
}
test('cores do not provide free conversion or death spread before components',()=>{
 const {w,h,foe}=arena('mage'),e=foe(),near=foe(120,20);h.core='pyromancer';addDot(w,e,h,'burn',10);const p={source:'skill',type:'fireball',damage:20,eventId:10};assert.equal(buildProjectileHit(w,p,e,h,{x:1,y:0}),20);assert.equal(e.statuses[0].damage,10);e.hp=1;w.damageEnemy(e,2,h);assert.equal(near.hp,1000);assert.equal(near.statuses.length,0);
 const other=arena(),war=other.h;war.core='berserker';war.resource=100;releaseBuildEnergy(other.w,war,{slot:1,dir:{x:1,y:0}});assert.equal(war.resource,100);assert.equal(other.w.delayed.length,0);
});
test('shield storage and release are separate investments with real expenditure',()=>{const {w,h,foe}=arena(),e=foe();h.forms=['aegis',null];h.passives.storage=2;h.shield=40;w.damageHero(h,20,e);assert.equal(h.storedGuard,9);const hp=e.hp;releaseBuildEnergy(w,h,{slot:1,dir:{x:1,y:0}});assert.equal(e.hp,hp);h.passives.guardRelease=1;releaseBuildEnergy(w,h,{slot:1,dir:{x:1,y:0}});assert.equal(h.storedGuard,0);assert.ok(e.hp<hp);});
test('bastion protects nearby allies while breach expends shield and advances',()=>{for(const branch of ['bastion','breach']){const {w,h,foe}=arena();h.forms=['aegis',null];h.evolved[0]=true;h.evolutionBranches[0]=branch;const ally=w.heroes[1];ally.x=100;foe(200);w.request(h,'skill1',{x:1,y:0});const a=h.action;w.advance(.2);if(branch==='bastion'){assert.ok(ally.shield>0);assert.ok(a.activeEnd>2);assert.equal(h.x,0);}else{w.advance(.6);assert.ok(h.x>100);assert.equal(h.shield,0);assert.equal(h.guardUntil,0);}}});
test('roving and anchored spin change attack rhythm and movement instead of only damage',()=>{const values={};for(const branch of ['roving','anchored']){const {w,h,foe}=arena();foe();h.forms=[null,'bloodspin'];h.evolved[1]=true;h.evolutionBranches[1]=branch;w.request(h,'skill2',{x:0,y:1});const a=h.action;w.advance(.7,[{x:0,y:1}]);values[branch]={y:h.y,pulses:a.pulses};if(branch==='roving')assert.ok(w.projectiles.some(p=>p.visual==='bloodspin'));else{w.advance(.9,[{x:0,y:1}]);assert.equal(a.pulses,8);}}assert.equal(values.roving.pulses,3);assert.ok(values.roving.y>values.anchored.y*2);});
test('wildfire spreads thin own burn; molten narrows coverage and consumes more existing burn',()=>{const results={};for(const branch of ['wildfire','molten']){const {w,h,foe}=arena('mage'),e=foe(),near=foe(140,90);h.passives.emberConsume=1;h.evolved[0]=true;h.evolutionBranches[0]=branch;addDot(w,e,h,'burn',10);w.request(h,'skill1',{x:1,y:0});const a=h.action;a.t=.4;updateBuildAction(w,h,a);const p=w.projectiles[0];results[branch]={damage:buildProjectileHit(w,p,e,h,{x:1,y:0}),radius:p.rangeBonus};assert.equal(near.statuses.some(s=>s.type==='burn'),branch==='wildfire');assert.equal(p.evolved,false);}assert.ok(results.molten.damage>results.wildfire.damage);assert.ok(results.molten.radius<results.wildfire.radius);});
test('crystal produces a fan whereas frostrail leaves three usable ground zones and one shard',()=>{for(const branch of ['crystal','frostrail']){const {w,h,foe}=arena('mage'),e=foe();h.forms=['icelance',null];h.evolved[0]=true;h.evolutionBranches[0]=branch;h.passives.iceFragments=1;e.chillBy={[h.id]:{brittleUntil:2,until:2}};w.request(h,'skill1',{x:1,y:0});h.action.t=.3;updateBuildAction(w,h,h.action);const p=w.projectiles[0];buildProjectileHit(w,p,e,h,{x:1,y:0});assert.equal(w.projectiles.filter(p=>p.fragment).length,branch==='crystal'?7:1);assert.equal(w.hazards.filter(f=>f.trail).length,branch==='frostrail'?3:0);}});
test('execution requires standing through longer windup and rewards isolated targets only',()=>{const {w,h,foe}=arena('archer'),e=foe(200);h.forms=['markedshot',null];h.evolved[0]=true;h.evolutionBranches[0]='execution';w.request(h,'skill1',{x:0,y:1});assert.equal(h.action.windup,.5);w.advance(.2,[{x:0,y:1}]);assert.equal(h.y,0);const p={damage:100,source:'skill',type:'pierce',branch:'execution'};assert.equal(buildProjectileHit(w,p,e,h,{x:1,y:0}),165);foe(250,20);assert.equal(buildProjectileHit(w,p,e,h,{x:1,y:0}),100);});
test('pursuit transfers only part of cashed marks after a kill, without copying teammate marks',()=>{const {w,h,foe}=arena('archer'),e=foe(),next=foe(180,30);h.core='sniper';h.passives.markCashout=2;e.hp=10;e.huntMarks={[h.id]:{stacks:5,last:0},1:{stacks:5,last:0}};const p={damage:20,source:'skill',type:'pierce',branch:'pursuit',form:'markedshot'};w.damageEnemy(e,buildProjectileHit(w,p,e,h,{x:1,y:0}),h,0,'skill');assert.equal(next.huntMarks[h.id].stacks,3);assert.equal(next.huntMarks[1],undefined);assert.equal(e.huntMarks[1].stacks,5);});
test('garrison keeps its first fixed shadow, skirmish relocates and has one delayed light volley',()=>{for(const branch of ['garrison','skirmish']){const {w,h}=arena('archer');h.forms=[null,'shadowvolley'];h.evolutionBranches[1]=branch;onBuildDodge(w,h);h.x=160;onBuildDodge(w,h);assert.equal(h.shadow.x,branch==='garrison'?0:160);assert.equal(h.shadow.life,branch==='garrison'?8:2.8);castShadow(w,h,{x:1,y:0});if(branch==='garrison')castShadow(w,h,{x:1,y:0});const count=w.projectiles.length;castShadow(w,h,{x:1,y:0});assert.equal(w.projectiles.length,count);assert.equal(w.delayed.length,branch==='skirmish'?1:0);}});
test('fragment chilling cannot reset its per-cast budget on each pierced target',()=>{const {w,h,foe}=arena('mage'),a=foe(),b=foe(150,30),c=foe(220,50);h.passives={iceFragments:1,frostReturn:1};const p={damage:20,source:'skill',type:'pierce',visual:'icelance',eventId:99};a.chillBy={[h.id]:{brittleUntil:2}};b.chillBy={[h.id]:{brittleUntil:2}};buildProjectileHit(w,p,a,h,{x:1,y:0});const shard=w.projectiles.find(p=>p.fragment);buildProjectileHit(w,shard,c,h,{x:1,y:0});buildProjectileHit(w,shard,c,h,{x:1,y:0});assert.equal(h.fragmentEvents[99],2);buildProjectileHit(w,p,b,h,{x:1,y:0});assert.equal(h.fragmentEvents[99],2);buildProjectileHit(w,shard,c,h,{x:1,y:0});assert.equal(h.fragmentEvents[99],2);});
test('field cooldown recovery consumes the same 35-percent refund budget',()=>{const {w,h}=arena('mage');h.passives.fieldFocus=3;h.cd=[3,0];h.refundBudget=[1.05,0];w.hazards=[{type:'coldfield',owner:h.id,x:0,y:0,r:100,life:50}];for(let i=0;i<20;i++){w.time=i;tickBuild(w,h,1);}assert.ok(Math.abs(h.cd[0]-1.95)<1e-9);});
test('mass kills heal harvest once per second while echo still spends its independent refund budget',()=>{const {w,h,foe}=arena();h.passives={harvest:2,echo:1};h.hp=100;h.cd=[5,5];h.refundBudget=[1.75,1.75];for(let i=0;i<3;i++){const e=foe(100+i*20);w.damageEnemy(e,2000,h);}assert.equal(h.hp,106);assert.ok(Math.abs(h.cd[0]-4.1)<1e-9);w.time=1;w.damageEnemy(foe(),2000,h);assert.equal(h.hp,112);assert.ok(Math.abs(h.cd[0]-3.8)<1e-9);});
test('boss eight-hit sustain and trash kills share one harvest healing cooldown',()=>{const {w,h,foe}=arena();h.passives.harvest=2;h.hp=100;w.damageEnemy(foe(),2000,h);const boss=w.createEnemy('thornking',200,0);boss.hp=boss.maxHp=100000;w.enemies.push(boss);w.time=.2;for(let i=0;i<8;i++)w.damageEnemy(boss,1,h,0,'attack',0,null,{eventId:100+i});assert.equal(h.hp,106);w.time=2.3;for(let i=0;i<8;i++)w.damageEnemy(boss,1,h,0,'attack',0,null,{eventId:200+i});assert.equal(h.hp,109);w.damageEnemy(foe(),2000,h);assert.equal(h.hp,109);w.time=3.3;w.damageEnemy(foe(),2000,h);assert.equal(h.hp,115);});
test('assist healing is timed independently for each contributing hero',()=>{const {w,h,foe}=arena(),ally=w.heroes[1];h.passives.harvest=1;ally.passives.harvest=2;h.hp=100;ally.hp=20;for(let i=0;i<3;i++){const e=foe();w.damageEnemy(e,1,h);w.damageEnemy(e,2000,ally);}assert.equal(h.hp,103);assert.equal(ally.hp,26);w.time=1;const e=foe();w.damageEnemy(e,1,h);w.damageEnemy(e,2000,ally);assert.equal(h.hp,106);assert.equal(ally.hp,32);});
test('executioner bleed kills have their own one-second real-heal limit and full-health kills do not consume it',()=>{const {w,h,foe}=arena('archer');h.core='executioner';h.crit=1;h.hp=h.maxHp;w.damageEnemy(foe(),2000,h);assert.equal(h.executionHealAt,undefined);h.hp=40;for(let i=0;i<3;i++)w.damageEnemy(foe(),2000,h);assert.equal(h.hp,48);w.time=.99;w.damageEnemy(foe(),2000,h);assert.equal(h.hp,48);w.time=1;w.damageEnemy(foe(),2000,h);assert.equal(h.hp,56);});
