import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/coop/model.js';
import {applyReward} from '../src/coop/builds.js';
import {SKILL_PAIRS} from '../src/coop/skill-pairs.js';
import {masteryActive,pairProjectileHit,steerPairProjectile,tickPairFields} from '../src/coop/pair-combat.js';
import {companionInput} from '../src/coop/ai.js';
import {HERO_ROLES} from '../src/coop/recruitment.js';
import {MAP} from '../src/coop/model.js';
function arena(role,slots,advanced=false){const w=new World(73);w.reset([role],1);w.pressure=null;w.obstacles=[];w.enemies=[];w.waveDuration=999;w.xpNext=1e9;const h=w.heroes[0];h.x=h.y=0;h.hp=h.maxHp=10000;h.attackCd=999;for(const slot of slots)for(let i=0;i<3;i++)applyReward(h,`active:${slot}`);if(advanced)for(const slot of slots)applyReward(h,`advance:${slot}`);for(const x of [100,180,260]){const e=w.createEnemy('mushroom',x,0);e.hp=e.maxHp=10000;e.cd=999;e.stats.speed=0;w.enemies.push(e);}return {w,h};}
for(const [key,pair] of Object.entries(SKILL_PAIRS))for(const advanced of [false,true])for(const slot of pair.slots)test(`${key} ${slot} ${advanced?'advanced':'base'} releases real damage through equipped input`,()=>{const {w,h}=arena(pair.role,pair.slots,advanced);const button=h.loadout.indexOf(slot);assert.equal(w.request(h,button?'skill2':'skill1',{x:1,y:0}),true);w.advance(1.5);assert.ok(h.damageDone>0,`${key}/${slot}: actual hit`);assert.ok(h.cd[slot]>0);assert.ok(w.enemies.every(e=>Number.isFinite(e.hp)));});
test('Replacing a skill requires a cancellable player-local choice and clears old owner objects',()=>{const {w,h}=arena('warrior',[0,1]);w.mode='upgrade';w.rewardType='skill';w.ready=[false];w.selection=[0];w.offers=[[{key:'active:2'}]];w.confirm(0);assert.equal(w.rewardMenus[0].type,'skill-replace');assert.deepEqual(h.skills,[3,3,0,0]);assert.equal(w.cancelReplacement(0),true);assert.deepEqual(w.offers[0],[{key:'active:2'}]);w.confirm(0);w.skillFields=[{owner:0,life:2}];w.choose(0,1);w.confirm(0);assert.deepEqual(h.loadout,[0,2]);assert.deepEqual(h.skills,[3,0,1,0]);assert.equal(w.skillFields.length,0);});
test('Wall charges only on real absorbed damage; shockwave never freezes a boss',()=>{const {w,h}=arena('warrior',[0,2],true);h.passives.storage=2;h.pairMastery.fortress=true;w.request(h,'skill1',{x:1,y:0});w.advance(.12);assert.ok(!h.wallCharge);w.damageHero(h,12,{x:50,y:0});assert.equal(h.wallCharge,true);w.advance(1.1);const boss=w.enemies[0];boss.boss=true;boss.x=100;boss.y=0;h.action=null;w.request(h,'skill2',{x:1,y:0});w.advance(.35);assert.equal(h.wallCharge,false);assert.equal(boss.freeze,0);assert.ok(boss.slow>0);assert.equal(w.skillFields.filter(f=>f.kind==='wave').length,2);});
test('Homing turns toward live targets; swept collision still stops at walls',()=>{const {w,h}=arena('mage',[2,3],true);const p=w.shoot(h,{x:1,y:0},'bolt',10,600,'skill');Object.assign(p,{homing:true,target:w.enemies[0].id,pair:'pair-arcane',muzzle:0});w.enemies[0].y=80;steerPairProjectile(w,p,.1);assert.ok(p.dy>0);w.obstacles=[{x:p.dx*35,y:p.dy*35,r:20}];w.updateProjectiles(.2);assert.ok(!w.projectiles.includes(p));assert.equal(h.damageDone,0);});
test('Arcane mastery increases finite salvos and does not repeat per missile hit',()=>{const counts=[];for(const mastery of [false,true]){const {w,h}=arena('mage',[2,3],true);h.passives.arcane=2;h.pairMastery.stars=mastery;let count=0;const shoot=w.shoot.bind(w);w.shoot=(...args)=>{count++;return shoot(...args);};w.request(h,'skill2',{x:1,y:0});w.advance(.5);w.request(h,'skill1',{x:1,y:0});w.advance(1.4);counts.push(count);}assert.equal(counts[1]-counts[0],6);assert.ok(counts[1]<40);});
test('Rail splitting and scatter ricochet are terminal; losing component suspends mastery',()=>{const {w,h}=arena('archer',[0,2],true),e=w.enemies[0];h.passives.focus=2;h.pairMastery.rail=true;e.pinnedBy={0:1};const p=w.shoot(h,{x:1,y:0},'pierce',40,800,'skill');Object.assign(p,{pair:'pair-rail',rail:true,hit:new Set([e.id])});pairProjectileHit(w,p,e,h,40);assert.equal(w.projectiles.length,3);pairProjectileHit(w,p,w.enemies[1],h,40);assert.equal(w.projectiles.length,3);assert.ok(w.projectiles.slice(1).every(p=>p.source==='proc'&&!p.rail));h.passives.focus=1;assert.equal(masteryActive(h,'rail'),false);});
test('Persistent fields freeze while paused, survive attribute rewards, and clear on death/wave',()=>{const {w,h}=arena('archer',[1,3],true);w.request(h,h.loadout.indexOf(3)?'skill2':'skill1',{x:1,y:0});w.advance(.28);const life=w.skillFields[0].life;w.pause();w.advance(2);assert.equal(w.skillFields[0].life,life);w.resume();w.beginReward('attribute');assert.equal(w.skillFields[0].life,life);h.down=true;tickPairFields(w,.1);assert.equal(w.skillFields.length,0);w.skillFields=[{owner:0,life:10}];w.settleWave();assert.equal(w.skillFields.length,0);});

test('Sword mastery needs a real hit before leaving a scar; one tornado adds only four blades',()=>{const {w,h}=arena('warrior',[1,3],true);h.passives.rageEdge=2;h.pairMastery.blades=true;w.enemies.forEach(e=>e.x+=900);w.request(h,h.loadout.indexOf(3)?'skill2':'skill1',{x:1,y:0});w.advance(.6);assert.equal(w.skillFields.filter(f=>f.kind==='scar').length,0);w.projectiles=[];const e=w.enemies[0];e.x=90;const p=w.shoot(h,{x:1,y:0},'pierce',40,800,'skill');p.pair='pair-ichi';pairProjectileHit(w,p,e,h,40);pairProjectileHit(w,p,e,h,40);assert.equal(w.skillFields.filter(f=>f.kind==='scar').length,1);let count=0;const shoot=w.shoot.bind(w);w.shoot=(...args)=>{count++;return shoot(...args);};h.action=null;w.request(h,h.loadout.indexOf(1)?'skill2':'skill1',{x:1,y:0});w.advance(1.1);assert.equal(count,8);});

test('Scatter rain synergy triggers once per cast and its ricochets cannot copy themselves',()=>{const {w,h}=arena('archer',[1,3],true);h.passives.volleyCharge=2;h.pairMastery.storm=true;w.skillFields=[{owner:0,kind:'rain',x:140,y:0,r:200,life:2}];for(const e of w.enemies.slice(0,2)){const p=w.shoot(h,{x:1,y:0},'arrow',20,600,'skill');Object.assign(p,{pair:'pair-fan',bounce:true,eventId:901,hit:new Set([e.id])});pairProjectileHit(w,p,e,h,20);}assert.equal(w.skillFields.length,2);const children=w.projectiles.filter(p=>p.source==='proc');assert.equal(children.length,2);assert.ok(children.every(p=>!p.bounce));});

test('Element mastery consumes only the caster chill and gives one steam burst',()=>{const {w,h}=arena('mage',[0,1],true),e=w.enemies[0],near=w.enemies[1];h.passives.ember=2;h.pairMastery.elements=true;e.chillBy={0:{until:5,stacks:2},1:{until:5,stacks:2}};const p={pair:'pair-fire',fireField:true,eventId:90,rangeBonus:1};const before=near.hp;pairProjectileHit(w,p,e,h,42);assert.ok(near.hp<before);assert.equal(e.chillBy[0].stacks,0);assert.equal(e.chillBy[1].stacks,2);const after=near.hp;pairProjectileHit(w,p,e,h,42);assert.equal(near.hp,after);});

test('AI maps extra skills to the equipped buttons and prepares the arcane station first',()=>{const {w,h}=arena('mage',[2,3],true);h.ai=true;w.enemies.forEach(e=>e.x+=250);const input=companionInput(w,h,HERO_ROLES.mage,MAP);assert.equal(input.skill1,false);assert.equal(input.skill2,true);w.advance(.3);assert.ok(w.skillFields.some(f=>f.kind==='orbit'));h.action=null;h.cd[3]=2;const next=companionInput(w,h,HERO_ROLES.mage,MAP);assert.equal(next.skill1,true);});

test('mastery blades bloom from the actual reachable sword scar, not empty space behind the hero',()=>{
 const {w,h}=arena('warrior',[1,3],true);h.passives.rageEdge=2;h.pairMastery.blades=true;w.skillFields=[{owner:0,kind:'scar',x:120,y:12,r:165,life:3,age:0}];
 w.request(h,h.loadout.indexOf(1)?'skill2':'skill1',{x:1,y:0});h.action.t=h.action.windup;
 return import('../src/coop/pair-combat.js').then(({updatePairAction})=>{updatePairAction(w,h,h.action);const children=w.projectiles.filter(p=>p.source==='proc');assert.equal(children.length,4);assert.ok(children.every(p=>p.x===120&&p.y===12&&p.muzzle===0));});
});
