import test from 'node:test';
import assert from 'node:assert/strict';
import {pressurePlan,partyPressure,pressureTick,createPressureState} from '../src/coop/pressure.js';
import {companionInput} from '../src/coop/ai.js';
import {World} from '../src/coop/model.js';

test('party scaling is pure and retains duration, rarity rules and per-member lifetime budgets',()=>{const plan=pressurePlan(1,1),before=structuredClone(plan);for(const n of [1,2,3]){const scaled=partyPressure(plan,n);assert.notEqual(scaled,plan);assert.equal(scaled.duration,plan.duration);assert.equal(scaled.interval,plan.interval);assert.deepEqual(scaled.spawnRadius,plan.spawnRadius);assert.equal(scaled.totalBudget,Math.round(plan.totalBudget*n/3));}assert.deepEqual(plan,before);assert.equal(partyPressure(plan,3).aliveCap,36);});
test('recruiting adds bounded crowd pressure instead of doubling it after the Boss shop',()=>{for(const room of [1,6,11,16,30])for(const wave of [1,2]){const p=[1,2,3].map(size=>partyPressure(pressurePlan(room,wave),size));for(const key of ['initial','targetAlive','aliveCap']){assert.ok(p[1][key]/p[0][key]<=1.85);assert.ok(p[2][key]/p[1][key]<=1.5);}assert.equal(p[2].totalBudget,pressurePlan(room,wave).totalBudget);}});
test('solo and duo retain crowds while each additional member increases active pressure and lifetime budget',()=>{for(let room=1;room<=20;room++)for(const wave of [1,2]){const p=[1,2,3].map(size=>partyPressure(pressurePlan(room,wave),size));for(const key of ['initial','targetAlive','aliveCap','totalBudget','timedBatch','refillBurst'])assert.ok(p[0][key]<p[1][key]&&p[1][key]<=p[2][key]);assert.ok(p.every(p=>p.initial<=p.targetAlive&&p.targetAlive<=p.aliveCap&&p.aliveCap<p.totalBudget));}const solo=partyPressure(pressurePlan(1,1),1);assert.equal(solo.initial,6);assert.equal(solo.aliveCap,14);assert.equal(solo.totalBudget,48);});
test('single-player waves replace deaths immediately and also accumulate monsters without a kill',()=>{const p=partyPressure(pressurePlan(1,1),1),start=pressureTick(p,createPressureState(p),{elapsed:0,alive:0});assert.equal(start.count,6);const death=pressureTick(p,start.state,{elapsed:.1,alive:5});assert.equal(death.count,1);const timed=pressureTick(p,death.state,{elapsed:p.interval,alive:6});assert.equal(timed.count,2);assert.equal(timed.reason,'timed');});
test('solo caps and lifetime budget prevent unbounded backlog and stop at the same time boundary',()=>{const p=partyPressure(pressurePlan(1,1),1);let s=createPressureState(p),sum=0;for(let i=0;i<200;i++){const next=pressureTick(p,s,{elapsed:i/120,alive:0});s=next.state;sum+=next.count;}assert.equal(sum,48);assert.equal(s.pendingRefill,0);const closed=pressureTick(p,createPressureState(p),{elapsed:p.duration,alive:0});assert.equal(closed.closed,true);assert.equal(closed.count,0);});
test('solo has forty seconds to clean up after spawning closes; party and Boss deadlines remain unchanged',()=>{const w=new World(9);w.reset(['mage','warrior'],1);assert.equal(w.enrageAt,w.waveDuration+40);w.reset(['mage','warrior'],2);assert.equal(w.enrageAt,w.waveDuration+20);w.room=10;w.enemies=[];w.spawnWave();assert.equal(w.enrageAt,150);w.reset(['mage','warrior'],1);w.room=10;w.enemies=[];w.spawnWave();assert.equal(w.enrageAt,150);});
function aiWorld(){const h={id:0,role:'mage',x:0,y:0,hp:90,maxHp:90,skills:[0,0],forms:[null,null],passives:{},cd:[0,0],dodgeCd:0,rangeBonus:1,pickupRadius:75,lastMove:{x:1,y:0},action:null};const w={time:0,heroes:[h],enemies:[],hazards:[],projectiles:[],bossWarnings:[],pickups:[],obstacles:[],lineClear:()=>true};return{w,h,role:{range:340},map:{x:1347,y:845}};}
test('a safe shot releases before a later warning while imminent impact still interrupts it',()=>{const {w,h,role,map}=aiWorld();w.enemies=[{id:20,x:250,y:0,hp:100,stats:{behavior:'melee'},action:{kind:'melee',x:0,y:0,r:45,t:0,windup:.22,hit:false}}];h.action={type:'attack',t:.1,windup:.15,duration:.5,fired:false};assert.equal(companionInput(w,h,role,map).dodge,false);w.enemies[0].action.windup=.07;assert.equal(companionInput(w,h,role,map).dodge,true);});
test('ranged AI reaches safe ground XP during a kite but ignores pickup paths through obstacles',()=>{const {w,h,role,map}=aiWorld();w.enemies=[{id:20,x:210,y:0,hp:100,stats:{behavior:'melee'}}];w.pickups=[{id:25,type:'xp',x:0,y:150,life:10}];const input=companionInput(w,h,role,map);assert.equal(h.aiIntent,'loot');assert.ok(input.y>.5);w.obstacles=[{x:0,y:75,r:30}];companionInput(w,h,role,map);assert.notEqual(h.aiIntent,'loot');});
test('a ranged hero approaches a sparse healing support instead of holding an unwinnable firing gap',()=>{const {w,h,role,map}=aiWorld();w.enemies=[{id:20,x:210,y:0,hp:100,stats:{behavior:'healer'}}];const input=companionInput(w,h,role,map);assert.equal(h.aiIntent,'approach');assert.ok(input.x>.8);});
