import test from 'node:test';
import assert from 'node:assert/strict';
import {createHero} from '../src/coop/recruitment.js';
import {ACTIVE,applyReward,skillPool} from '../src/coop/builds.js';
import {SKILL_PAIRS,pairReady,masteryReady} from '../src/coop/skill-pairs.js';
import {XP_CHANCE,GOLD_CHANCE,POTION_CHANCE,xpRequired} from '../src/coop/loot.js';
test('Every class has four distinct base skills, starts empty and equips only two',()=>{for(const role of ['warrior','mage','archer']){const h=createHero(role,0);assert.equal(ACTIVE[role].length,4);assert.equal(new Set(ACTIVE[role].map(s=>s.type)).size,4);assert.equal(h.skills.filter(Boolean).length,0);applyReward(h,'active:2');applyReward(h,'active:3');assert.deepEqual(h.loadout,[2,3]);assert.equal(applyReward(h,'active:0').status,'skill-replace-required');assert.equal(h.skills[0],0);assert.equal(applyReward(h,'active:0',{replaceSkill:2}).ok,true);assert.equal(h.skills[2],0);assert.deepEqual(h.loadout,[0,3]);}});
test('Pair advancement needs both equipped level II skills and a separate later reward',()=>{for(const [key,p] of Object.entries(SKILL_PAIRS)){const h=createHero(p.role,0);for(const slot of p.slots){applyReward(h,`active:${slot}`);applyReward(h,`active:${slot}`);}assert.equal(pairReady(h,p.slots[0]),true);assert.equal(skillPool(h,{clears:7}).some(o=>o.kind==='advance'),false);assert.equal(skillPool(h,{clears:8}).filter(o=>o.kind==='advance').length,2);assert.equal(applyReward(h,`advance:${p.slots[0]}`).ok,true);assert.equal(applyReward(h,`advance:${p.slots[0]}`).ok,false);assert.equal(h.skillAdvances[p.slots[1]],false);assert.equal(masteryReady(h,key),false);}});
test('Mastery requires both III advances and a component II; swapping breaks qualification',()=>{for(const [key,p] of Object.entries(SKILL_PAIRS)){const h=createHero(p.role,0);for(const s of p.slots)for(let i=0;i<3;i++)applyReward(h,`active:${s}`);for(const s of p.slots)applyReward(h,`advance:${s}`);h.passives[p.component]=2;assert.equal(masteryReady(h,key),true);assert.equal(skillPool(h,{clears:15}).some(o=>o.kind==='mastery'),false);assert.equal(skillPool(h,{clears:16}).some(o=>o.key===`mastery:${key}`),true);assert.equal(applyReward(h,`mastery:${key}`).ok,true);assert.equal(applyReward(h,`mastery:${key}`).ok,false);}});
test('Early XP curve eases slightly and normal drops/pickup increase with late curve retained',()=>{assert.equal(createHero('warrior',0).pickupRadius,105);assert.deepEqual([1,2,3,4,5].map(xpRequired),[28,62,100,140,184]);assert.equal(xpRequired(10),374);assert.equal(XP_CHANCE[0],.66);assert.equal(GOLD_CHANCE[0],.04);assert.equal(POTION_CHANCE[0],.011);});

test('Legacy reshaping removes pair advancement and disables its mastery',()=>{const h=createHero('warrior',0);for(const s of [0,2])for(let i=0;i<3;i++)applyReward(h,`active:${s}`);applyReward(h,'advance:0');applyReward(h,'advance:2');h.passives.storage=2;assert.equal(applyReward(h,'reshape:form:0:aegis').ok,true);assert.equal(h.skillAdvances[0],false);assert.equal(masteryReady(h,'fortress'),false);assert.equal(pairReady(h,0),false);});

test('Advanced fire is a real burn source even without ember',()=>{const h=createHero('mage',0);for(const s of [0,1])for(let i=0;i<2;i++)applyReward(h,`active:${s}`);applyReward(h,'advance:0');assert.ok(skillPool(h,{clears:12}).some(o=>o.key==='passive:detonate'));});
