import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/coop/model.js';
import {createHero} from '../src/coop/recruitment.js';
import {PASSIVES} from '../src/coop/builds.js';
import {xpRequired} from '../src/coop/loot.js';

function arena(humans=1){const w=new World(29);w.reset(['warrior','mage'],humans);w.pressure=null;w.enemies=[];w.effects=[];w.obstacles=[];w.waveDuration=999;w.heroes.forEach(h=>{h.ai=h.id>=humans;h.attackCd=999;h.x=h.id*500;h.y=0;});return w;}
function foe(w,x=0,y=0){const e=w.createEnemy('seedling',x,y);e.cd=999;e.hp=e.maxHp=500;w.enemies.push(e);return e;}
test('a killed monster is replaced in the same simulation frame, even above target population',()=>{const w=new World(19);w.reset();w.waveElapsed=6;w.refreshPressure();const n=w.enemies.length,k=w.waveSpawned;const e=w.enemies[0];w.damageEnemy(e,9999,w.heroes[0]);w.advance(1/120);assert.equal(w.waveSpawned,k+1);assert.equal(w.enemies.length,n);});
test('contact damage from a crowd uses one shared invulnerability window and spawn grace',()=>{const w=arena(),h=w.heroes[0];w.moveActor=()=>{};for(let i=0;i<20;i++)foe(w);w.resolveBodies();assert.equal(h.hp,198);w.resolveBodies();assert.equal(h.hp,198);h.invuln=0;w.enemies.forEach(e=>e.spawnGrace=.3);w.resolveBodies();assert.equal(h.hp,198);w.enemies[0].spawnGrace=0;w.resolveBodies();assert.equal(h.hp,196);});
test('death grants no XP; pickup range upgrade collects real ground XP and preserves overflow',()=>{const w=arena(),h=w.heroes[0];w.random=()=>0;const e=foe(w,90);w.damageEnemy(e,9999,h);assert.equal(w.xp,0);w.updatePickups(.1);assert.equal(w.xp,0);w.offers=[[{key:'pickup'}],[],[]];w.mode='upgrade';w.rewardType='attribute';w.ready=[false,true,true];w.selection=[0];w.confirm(0);assert.equal(h.pickupRadius,95);w.updatePickups(.3);assert.equal(w.xp,1);assert.equal(w.gold,2);w.dropPickup({type:'xp',value:xpRequired(1)+5,x:h.x,y:h.y});w.updatePickups(.1);w.advance(1/120);assert.equal(w.mode,'upgrade');assert.equal(w.level,2);assert.equal(w.xp,6);});
test('two humans must each finish replacement; cancel spends no card or reroll',()=>{const w=arena(2),h=w.heroes[0];h.passives={needleMagazine:1,mineShoes:1,orbitBlades:1,kineticWheel:1};w.beginReward('skill');w.offers[0]=[{key:'passive:refractLens',...PASSIVES.refractLens}];w.confirm(0);assert.equal(w.offers[0].length,4);assert.equal(w.rewardMenus[0].type,'replace');const invalid=w.offers[0].findIndex(o=>o.key==='replace:needleMagazine');assert.equal(w.offers[0][invalid].disabled,true);w.choose(0,invalid);w.confirm(0);assert.equal(w.ready[0],false);assert.ok(w.rewardError);assert.equal(w.cancelReplacement(0),true);assert.equal(h.rerolls,3);assert.equal(h.passives.refractLens,undefined);w.confirm(0);w.choose(0,w.offers[0].findIndex(o=>o.key==='replace:mineShoes'));w.confirm(0);assert.equal(h.passives.refractLens,1);assert.equal(h.passives.mineShoes,undefined);assert.equal(w.mode,'upgrade');assert.equal(w.ready[0],true);assert.equal(w.ready[1],false);w.confirm(1);assert.equal(w.mode,'play');});
test('Boss route reveals rewards only after a choice; reshape preserves levels and clears owned objects',()=>{const w=arena(),h=w.heroes[0];w.room=10;w.bossRoom=true;w.clears=18;h.core='bulwark';h.skills=[3,2];w.pets=[{id:77,owner:0,kind:'dog',life:9,max:9}];w.beginReward('skill');assert.equal(w.rewardMenus[0].type,'route');assert.equal(w.offers[0].some(o=>o.quality==='legendary'),false);w.choose(0,w.offers[0].findIndex(o=>o.key==='route:core'));w.confirm(0);assert.equal(w.offers[0].length,2);assert.equal(w.rewardMenus[0].type,'reshape');w.confirm(0);assert.notEqual(h.core,'bulwark');assert.deepEqual(h.skills,[3,2]);assert.equal(h.reshaped,true);assert.equal(w.pets.length,0);assert.equal(w.mode,'shop');w.leaveShop(0);assert.equal(w.mode,'complete');});
test('twentieth Boss clear ends standard adventure; endless starts room 21 with collected gold',()=>{const w=arena();w.room=20;w.bossRoom=true;w.gold=71;w.waveElapsed=0;w.waveDuration=0;w.waveTimer=2;w.advance(1/120);assert.equal(w.mode,'shop');w.leaveShop(0);assert.equal(w.mode,'victory');w.startEndless();assert.equal(w.room,21);assert.equal(w.gold,71);assert.equal(w.endless,true);assert.equal(w.mode,'play');});
test('shieldless directional guard primes exactly one 45-percent basic counter',()=>{const w=arena(),h=w.heroes[0],e=foe(w,100);h.core='bulwark';h.skills=[1,0];w.request(h,'skill1',{x:1,y:0});w.damageHero(h,20,e);assert.equal(h.hp,190);assert.equal(h.counterReady,true);const hp=e.hp;w.damageEnemy(e,10,h,0,'attack',0,null,{eventId:81});assert.ok(Math.abs(hp-e.hp-12.325)<1e-8);w.damageEnemy(e,10,h,0,'attack',0,null,{eventId:82});assert.ok(Math.abs(hp-e.hp-20.825)<1e-8);});
test('wound cashout damages only its original target and is not an accidental area skill',()=>{const w=arena(),h=w.heroes[0],a=foe(w,100),b=foe(w,120);w.delayed=[{type:'woundburst',owner:0,target:a.id,damage:23,delay:.001}];w.advance(1/120);assert.equal(a.hp,477);assert.equal(b.hp,500);});
test('repeated attacks from the same enemy count as distinct precise dodges',()=>{const w=arena(),h=w.heroes[0],e=foe(w,200);h.skills=[1,0];h.passives={riskEcho:1};h.action={type:'dodge'};h.invuln=.2;e.action={attackId:71};w.damageHero(h,10,e);assert.ok(h.universal.riskUntil>0);w.time=7;e.action={attackId:72};h.universal.riskUntil=0;w.damageHero(h,10,e);assert.ok(h.universal.riskUntil>w.time);});
test('restoration is bounded to completed waves and room transition, never an attribute reward or frame',()=>{const w=arena(),h=w.heroes[0];h.hp=50;w.advance(.1);assert.equal(h.hp,50);w.beginReward('attribute');w.offers[0]=[{key:'power'}];w.confirm(0);assert.equal(h.hp,50);w.beginReward('skill');w.confirm(0);assert.equal(h.hp,80);w.mode='complete';w.nextRoom();assert.equal(h.hp,104);w.nextRoom();assert.equal(h.hp,104);});
test('a single learned active cannot lead to an empty or one-card reshape fork',()=>{const w=arena(),h=w.heroes[0];w.room=10;w.bossRoom=true;h.skills=[1,0];h.core='bulwark';w.beginReward('skill');assert.ok(!w.offers[0].some(o=>o.key==='route:form'));assert.ok(w.offers[0].some(o=>o.key==='route:core'));});

test('final Boss cleanup revives once, clears hazards and keeps shared loot before endless',()=>{const w=arena();w.room=20;w.bossRoom=true;w.waveDuration=0;w.waveTimer=2;w.heroes.push(createHero('mage',1,{ai:true}));const h=w.heroes[1];h.down=true;h.hp=0;h.revive=1.5;w.hazards=[{type:'fire',owner:0,x:900,y:900,r:10,life:2,timer:3}];w.delayed=[{type:'fan',owner:0,delay:3}];w.dropPickup({type:'gold',x:-900,y:-500,value:7});w.advance(1/120);assert.equal(w.mode,'shop');w.leaveShop(0);assert.equal(w.mode,'victory');assert.equal(h.down,false);assert.equal(h.hp,h.maxHp*.35);assert.equal(h.revive,0);assert.equal(w.hazards.length,0);assert.equal(w.delayed.length,0);assert.equal(w.pickups[0].value,7);w.startEndless();assert.ok(Math.abs(h.hp-h.maxHp*.47)<1e-8);});
