export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const len=(x,y)=>Math.hypot(x,y);
export const dist=(a,b)=>len(a.x-b.x,a.y-b.y);
export const norm=(x,y)=>{const l=len(x,y);return l?{x:x/l,y:y/l}:{x:0,y:0};};
export const dir8=(x,y)=>((Math.round(Math.atan2(y,x)/(Math.PI/4))+8)%8);
export const ROLES={warrior:{name:'战士',hp:140,speed:175,range:100,damage:19,interval:.57,skills:['盾冲','旋风斩'],cd:[3.2,5]},mage:{name:'法师',hp:90,speed:170,range:340,damage:13,interval:.76,skills:['火球','冰霜环'],cd:[2.8,5]},archer:{name:'弓手',hp:105,speed:188,range:370,damage:12,interval:.5,skills:['贯穿箭','箭雨扇射'],cd:[3,4.5]}};
export function analog(x,y,dead=.18){const m=len(x,y);if(m<=dead)return{x:0,y:0};const n=norm(x,y),s=clamp((m-dead)/(1-dead),0,1);return{x:n.x*s,y:n.y*s};}
const baseInput=()=>({x:0,y:0,dodge:false,skill1:false,skill2:false});
const OBSTACLES=[{x:-415,y:-150,r:35},{x:420,y:150,r:40},{x:100,y:-300,r:26}];
export class World{
 constructor(seed=17){this.seed=seed;this.mode='menu';this.reset(['warrior','mage']);this.mode='menu';}
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 reset(roles=['warrior','mage']){if(roles[0]===roles[1]||roles.some(r=>!ROLES[r]))throw Error('Two distinct roles required');this.time=0;this.tick=0;this.accumulator=0;this.pendingEdges=[{},{}];this.mode='play';this.reason='';this.room=1;this.wave=1;this.level=1;this.kills=0;this.xp=0;this.enemies=[];this.projectiles=[];this.effects=[];this.events=[];this.nextId=10;this.waveTimer=0;this.obstacles=OBSTACLES;this.ready=[false,false];this.selection=[0,0];this.offers=[];this.camera={x:0,y:0,zoom:1};this.shake=0;this.options={feedback:true,shake:true,sound:true};
  const all=[...roles,...Object.keys(ROLES).filter(r=>!roles.includes(r))];this.heroes=all.map((role,i)=>({id:i,role,ai:i===2,x:-140+i*120,y:i===2?110:35,hp:ROLES[role].hp,maxHp:ROLES[role].hp,power:1,speedBonus:1,skillPower:1,rangeBonus:1,cd:[0,0],dodgeCd:0,attackCd:0,action:null,move:{x:0,y:0},lastMove:{x:1,y:0},face:0,stride:0,hitFlash:0,visualStop:0,invuln:0,down:false,revive:0,buffer:null,damageDone:0}));this.spawnWave();}
 spawnWave(){this.waveTimer=0;const count=this.wave===1?5:6;for(let i=0;i<count;i++){const a=i/count*Math.PI*2+.4;this.enemies.push({id:this.nextId++,kind:i%3===0?'mushroom':'goblin',x:Math.cos(a)*420,y:Math.sin(a)*265,hp:i%3===0?85+this.room*12:39+this.room*6,maxHp:i%3===0?85+this.room*12:39+this.room*6,action:null,cd:1+i*.19,hitFlash:0,visualStop:0,slow:0,face:4,stride:0,knock:{x:0,y:0}});}}
 pause(reason='暂停'){if(this.mode==='play'||this.mode==='upgrade'){this.resumeMode=this.mode;this.mode='paused';this.reason=reason;this.clearBuffers();}}
 resume(){if(this.mode==='paused'){this.mode=this.resumeMode||'play';this.reason='';this.clearBuffers();}}
 clearBuffers(){this.pendingEdges=[{},{}];for(const h of this.heroes){h.buffer=null;h.move={x:0,y:0};}}
 emit(type,data={}){this.events.push({type,...data});if(this.events.length>80)this.events.shift();}
 request(h,type,input){if(h.down)return false;const moving=len(input.x,input.y)>.01;const v=moving?norm(input.x,input.y):h.lastMove;h.buffer={type,expires:this.time+.14,dir:{...v}};return this.consume(h);}
 consume(h){const b=h.buffer;if(!b)return false;if(this.time>b.expires){h.buffer=null;return false;}const a=h.action;if(b.type==='dodge'){
   if(h.dodgeCd>0||a?.type==='dodge'||(a&&a.type!=='attack'&&a.t<a.duration*.55))return false;
   h.action={type:'dodge',t:0,duration:.29,dir:b.dir,hit:new Set()};h.invuln=.15;h.dodgeCd=.85;h.buffer=null;this.emit('dodge',{id:h.id});return true;
  }
  const s=b.type==='skill1'?0:1;if(h.cd[s]>0||(a&&a.type!=='attack'))return false;
  const target=this.nearest(h,520);const d=target?norm(target.x-h.x,target.y-h.y):b.dir;
  const type=h.role==='warrior'?(s===0?'bash':'spin'):h.role==='mage'?(s===0?'fireball':'frost'):(s===0?'pierce':'fan');
  h.action={type,t:0,duration:type==='bash'?.39:type==='spin'?.53:.38,dir:type==='bash'?b.dir:d,hit:new Set(),fired:false};h.cd[s]=ROLES[h.role].cd[s];h.buffer=null;h.face=dir8(h.action.dir.x,h.action.dir.y);this.emit('skill',{id:h.id,skill:type});return true;
 }
 nearest(h,range=Infinity){let best=null,d=range;for(const e of this.enemies){const n=dist(h,e);if(e.hp>0&&n<d&&this.lineClear(h,e)){best=e;d=n;}}return best;}
 lineClear(a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;return !this.obstacles.some(o=>{const t=l?clamp(((o.x-a.x)*dx+(o.y-a.y)*dy)/l,0,1):0;return len(a.x+t*dx-o.x,a.y+t*dy-o.y)<o.r;});}
 moveActor(h,dx,dy,r=17){h.x=clamp(h.x+dx,-550+r,550-r);h.y=clamp(h.y+dy,-345+r,345-r);for(const o of this.obstacles){const d=dist(h,o),rr=r+o.r;if(d<rr){const n=d?norm(h.x-o.x,h.y-o.y):{x:1,y:0};h.x=o.x+n.x*rr;h.y=o.y+n.y*rr;}}}
 damageEnemy(e,n,h,knock=70){if(e.hp<=0)return;e.hp-=n;h.damageDone+=n;e.hitFlash=.13;e.visualStop=.04;h.visualStop=.035;const d=norm(e.x-h.x,e.y-h.y);e.knock={x:d.x*knock,y:d.y*knock};this.effects.push({type:'number',x:e.x,y:e.y,text:String(Math.round(n)),life:.7,max:.7,color:'#fff0b4'});this.emit('hit',{id:h.id,heavy:n>=28});if(n>=28)this.shake=Math.min(.12,this.shake+.05);if(e.hp<=0){this.kills++;this.xp++;this.effects.push({type:'poof',x:e.x,y:e.y,life:.35,max:.35});this.emit('kill',{id:h.id});}}
 damageHero(h,n,e){if(h.down||h.invuln>0)return;h.hp=Math.max(0,h.hp-n);h.invuln=.55;h.hitFlash=.2;this.emit('hurt',{id:h.id});const d=norm(h.x-e.x,h.y-e.y);this.moveActor(h,d.x*18,d.y*18);if(!h.hp){h.down=true;h.action=null;h.buffer=null;this.emit('down',{id:h.id});}}
 shoot(h,dir,type,damage,speed=470){this.projectiles.push({id:this.nextId++,owner:h.id,type,x:h.x+dir.x*25,y:h.y+dir.y*25,dx:dir.x,dy:dir.y,damage,speed,life:1.7,hit:new Set()});}
 advance(seconds,inputs=[{},{}]){if(this.mode!=='play')return;for(let p=0;p<2;p++)for(const k of ['dodge','skill1','skill2'])this.pendingEdges[p][k] ||= !!inputs[p]?.[k];this.accumulator+=Math.max(0,seconds);while(this.accumulator+1e-9>=1/120){this.accumulator-=1/120;const sample=[0,1].map(p=>({...inputs[p],...this.pendingEdges[p]}));this.pendingEdges=[{dodge:false,skill1:false,skill2:false},{dodge:false,skill1:false,skill2:false}];this.step(1/120,sample);}}
 step(dt,inputs){if(this.mode!=='play')return;this.time+=dt;this.tick++;this.shake=Math.max(0,this.shake-dt);this.effects=this.effects.filter(f=>(f.life-=dt)>0);
  for(const h of this.heroes){let input={...baseInput(),...(inputs[h.id]||{})};if(h.ai)input=this.aiInput(h);h.cd=h.cd.map(t=>Math.max(0,t-dt));h.dodgeCd=Math.max(0,h.dodgeCd-dt);h.attackCd=Math.max(0,h.attackCd-dt);h.invuln=Math.max(0,h.invuln-dt);h.hitFlash=Math.max(0,h.hitFlash-dt);h.visualStop=Math.max(0,h.visualStop-dt);
   if(h.down){const helper=this.heroes.some(p=>!p.down&&p.id!==h.id&&dist(p,h)<82);h.revive=helper?h.revive+dt:Math.max(0,h.revive-dt*.5);if(h.revive>=2){h.down=false;h.hp=h.maxHp*.45;h.revive=0;h.invuln=1;this.emit('revive',{id:h.id});}continue;}
   const m=len(input.x,input.y);if(m>1){input.x/=m;input.y/=m;}h.move={x:input.x,y:input.y};if(m>.01)h.lastMove=norm(input.x,input.y);
   if(input.dodge)this.request(h,'dodge',input);else if(input.skill1)this.request(h,'skill1',input);else if(input.skill2)this.request(h,'skill2',input);this.consume(h);
   const a=h.action;const speed=ROLES[h.role].speed*h.speedBonus;
   if(a&&(a.type==='dodge'||a.type==='bash')){const old=a.t;a.t=Math.min(a.duration,a.t+dt);const ease=t=>1-(1-t)**2;const travel=a.type==='dodge'?112:145;const d=(ease(a.t/a.duration)-ease(old/a.duration))*travel;this.moveActor(h,a.dir.x*d,a.dir.y*d);h.face=dir8(a.dir.x,a.dir.y);}
   else{this.moveActor(h,input.x*speed*dt,input.y*speed*dt);if(m>.01){h.stride+=Math.min(1,m)*speed*dt/62;if(!a)this.faceToward(h,input.x,input.y);}if(a)a.t+=dt;}
   // Keep both players inside a shared camera range without teleporting the other player.
   if(!h.ai){const other=this.heroes[1-h.id],dx=h.x-other.x,dy=h.y-other.y;if(!other.down){const spread=len(dx,dy*.72);if(spread>820){const k=820/spread;h.x=other.x+dx*k;h.y=other.y+dy*k;}}}
   if(a){const t=a.t;
    if(a.type==='attack'&&!a.fired&&t>=a.duration*.33){a.fired=true;if(h.role==='warrior'){for(const e of this.enemies){const n=norm(e.x-h.x,e.y-h.y);if(dist(e,h)<112&&n.x*a.dir.x+n.y*a.dir.y>-.1&&this.lineClear(h,e))this.damageEnemy(e,ROLES[h.role].damage*h.power,h);}}else this.shoot(h,a.dir,h.role==='mage'?'bolt':'arrow',ROLES[h.role].damage*h.power);}
    if(a.type==='bash'&&t>.045){for(const e of this.enemies)if(!a.hit.has(e.id)&&dist(h,e)<68){a.hit.add(e.id);this.damageEnemy(e,36*h.skillPower,h,260);}}
    if(a.type==='spin'&&t>.12){for(const e of this.enemies)if(!a.hit.has(e.id)&&dist(h,e)<148){a.hit.add(e.id);this.damageEnemy(e,38*h.skillPower,h,150);}}
    if(['fireball','frost','pierce','fan'].includes(a.type)&&!a.fired&&t>=.105){a.fired=true;if(a.type==='frost'){this.effects.push({type:'frost',x:h.x,y:h.y,r:185*h.rangeBonus,life:.48,max:.48});for(const e of this.enemies)if(dist(h,e)<185*h.rangeBonus){e.slow=2.2;this.damageEnemy(e,23*h.skillPower,h,100);}}else if(a.type==='fan'){const angle=Math.atan2(a.dir.y,a.dir.x);for(const off of [-.34,-.17,0,.17,.34])this.shoot(h,{x:Math.cos(angle+off),y:Math.sin(angle+off)},'arrow',20*h.skillPower,560);}else this.shoot(h,a.dir,a.type,a.type==='fireball'?42*h.skillPower:45*h.skillPower, a.type==='fireball'?390:650);}
    if(t>=a.duration)h.action=null;
   }
   if(!h.action&&h.attackCd<=0){const target=this.nearest(h,ROLES[h.role].range);if(target){const d=norm(target.x-h.x,target.y-h.y);h.face=dir8(d.x,d.y);h.action={type:'attack',dir:d,t:0,duration:ROLES[h.role].interval*.85,fired:false,hit:new Set()};h.attackCd=ROLES[h.role].interval;}}
  }
  for(const p of this.projectiles){p.life-=dt;const ox=p.x,oy=p.y;p.x+=p.dx*p.speed*dt;p.y+=p.dy*p.speed*dt;if(!this.lineClear({x:ox,y:oy},p)){p.life=0;continue;}for(const e of this.enemies){if(e.hp<=0||p.hit.has(e.id))continue;const dx=p.x-ox,dy=p.y-oy,l=dx*dx+dy*dy,t=l?clamp(((e.x-ox)*dx+(e.y-oy)*dy)/l,0,1):0;if(len(ox+t*dx-e.x,oy+t*dy-e.y)<(e.kind==='mushroom'?32:23)){p.hit.add(e.id);const h=this.heroes[p.owner];this.damageEnemy(e,p.damage,h,p.type==='pierce'?150:65);if(p.type==='fireball'){this.effects.push({type:'blast',x:e.x,y:e.y,r:95,life:.4,max:.4});for(const other of this.enemies)if(other!==e&&other.hp>0&&dist(e,other)<95)this.damageEnemy(other,p.damage*.65,h,100);}if(p.type!=='pierce'){p.life=0;break;}}}}
  this.projectiles=this.projectiles.filter(p=>p.life>0&&Math.abs(p.x)<570&&Math.abs(p.y)<365);
  this.enemies=this.enemies.filter(e=>e.hp>0);
  for(const e of this.enemies){e.hitFlash=Math.max(0,e.hitFlash-dt);e.visualStop=Math.max(0,e.visualStop-dt);e.slow=Math.max(0,e.slow-dt);this.moveActor(e,e.knock.x*dt,e.knock.y*dt,22);e.knock.x*=Math.exp(-dt*10);e.knock.y*=Math.exp(-dt*10);e.cd=Math.max(0,e.cd-dt);const alive=this.heroes.filter(h=>!h.down);const target=alive.sort((a,b)=>dist(a,e)-dist(b,e))[0];if(!target)continue;
   if(e.action){e.action.t+=dt;if(!e.action.hit&&e.action.t>=e.action.windup){e.action.hit=true;for(const h of this.heroes)if(!h.down&&dist(h,e.action)<e.action.r)this.damageHero(h,e.kind==='mushroom'?24:12,e);this.effects.push({type:'impact',x:e.action.x,y:e.action.y,r:e.action.r,life:.25,max:.25});}if(e.action.t>e.action.windup+.32)e.action=null;}
   else if(dist(e,target)<(e.kind==='mushroom'?108:75)&&e.cd===0){e.action={t:0,x:target.x,y:target.y,r:e.kind==='mushroom'?90:57,windup:e.kind==='mushroom'?.7:.52,hit:false};e.cd=e.kind==='mushroom'?2.15:1.7;}
   else if(dist(e,target)>55){const v=norm(target.x-e.x,target.y-e.y);const sp=(e.kind==='mushroom'?58:85)*(e.slow>0?.38:1);this.moveActor(e,v.x*sp*dt,v.y*sp*dt,22);e.face=dir8(v.x,v.y);e.stride+=dt*sp/60;}
  }
  // Separate foes so telegraphs and silhouettes remain legible.
  for(let i=0;i<this.enemies.length;i++)for(let j=i+1;j<this.enemies.length;j++){const a=this.enemies[i],b=this.enemies[j],d=dist(a,b);if(d<47){const v=d?norm(a.x-b.x,a.y-b.y):{x:1,y:0};this.moveActor(a,v.x*(47-d)*.5,v.y*(47-d)*.5,22);this.moveActor(b,-v.x*(47-d)*.5,-v.y*(47-d)*.5,22);}}
  if(this.heroes.every(h=>h.down)){this.mode='defeat';this.clearBuffers();return;}
  if(!this.enemies.length){this.waveTimer+=dt;if(this.waveTimer>1.1){if(this.wave===1){this.wave=2;this.spawnWave();this.emit('wave');}else this.beginUpgrade();}}
  const ps=this.heroes.slice(0,2),cx=(ps[0].x+ps[1].x)/2,cy=(ps[0].y+ps[1].y)/2;const z=clamp(1.1-Math.max(Math.abs(ps[0].x-ps[1].x)/1800,Math.abs(ps[0].y-ps[1].y)/1500),.85,1.05);const k=1-Math.exp(-dt*3);this.camera.x+=(cx*.26-this.camera.x)*k;this.camera.y+=(cy*.22-this.camera.y)*k;if(Math.abs(z-this.camera.zoom)>.025)this.camera.zoom+=(z-this.camera.zoom)*k;
 }
 faceToward(h,x,y){const a=Math.atan2(y,x),old=h.face*Math.PI/4;const diff=Math.atan2(Math.sin(a-old),Math.cos(a-old));if(Math.abs(diff)>Math.PI/8+.08)h.face=dir8(x,y);}
 aiInput(h){const n=this.heroes.find(p=>p.down),target=this.nearest(h),leader=n||this.heroes.find(p=>!p.ai&&!p.down)||h;let dest=leader;
  if(!n&&target){const d=dist(h,target),ideal=h.role==='warrior'?65:240;if(d>ideal+25)dest=target;else if(d<ideal-60){const v=norm(h.x-target.x,h.y-target.y);dest={x:h.x+v.x*100,y:h.y+v.y*100};}else dest=h;}
  const v=dist(h,dest)>(n?48:dest===target?0:90)?norm(dest.x-h.x,dest.y-h.y):{x:0,y:0};for(const ally of this.heroes){const d=dist(h,ally);if(ally!==h&&!ally.down&&d<48){const away=d?norm(h.x-ally.x,h.y-ally.y):{x:1,y:0};v.x+=away.x*.8;v.y+=away.y*.8;}}if(!this.lineClear(h,{x:h.x+v.x*75,y:h.y+v.y*75})){const a=Math.atan2(v.y,v.x);const candidates=[a+1.15,a-1.15].map(t=>({x:Math.cos(t),y:Math.sin(t)})).filter(p=>this.lineClear(h,{x:h.x+p.x*75,y:h.y+p.y*75})).sort((a,b)=>dist({x:h.x+a.x*75,y:h.y+a.y*75},dest)-dist({x:h.x+b.x*75,y:h.y+b.y*75},dest));if(candidates.length){v.x=candidates[0].x;v.y=candidates[0].y;}}const danger=this.enemies.some(e=>e.action&&!e.action.hit&&dist(h,e.action)<e.action.r+8&&e.action.t>e.action.windup*.5);return{x:v.x,y:v.y,dodge:danger&&h.dodgeCd===0,skill1:!!target&&h.cd[0]===0,skill2:!!target&&dist(h,target)<190&&h.cd[1]===0};}
 beginUpgrade(){this.mode='upgrade';this.level++;this.xp=0;this.clearBuffers();this.projectiles=[];this.ready=[false,false];this.selection=[0,0];this.offers=this.heroes.slice(0,2).map(h=>{const pool=[{key:'power',title:'磨砺武器',desc:'普通攻击伤害 +18%',icon:'sword'},{key:'hp',title:'坚韧之心',desc:'生命上限 +25，回复 35',icon:'heart'},{key:'speed',title:'轻盈步伐',desc:'移动速度 +10%',icon:'boot'},{key:'skill',title:'专注训练',desc:'两个主动技能伤害 +20%',icon:'focus'},{key:'heal',title:'林间补给',desc:'回复 55 生命',icon:'heal'}];for(let i=pool.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,3);});const ai=this.heroes[2];ai.power*=1.18;ai.hp=Math.min(ai.maxHp,ai.hp+35);ai.down=false;}
 choose(slot,index){if(this.mode==='upgrade'&&!this.ready[slot])this.selection[slot]=clamp(index,0,2);}
 confirm(slot){if(this.mode!=='upgrade'||this.ready[slot])return;const h=this.heroes[slot],o=this.offers[slot][this.selection[slot]];if(o.key==='power')h.power*=1.18;if(o.key==='hp'){h.maxHp+=25;h.hp=Math.min(h.maxHp,h.hp+35);}if(o.key==='speed')h.speedBonus*=1.1;if(o.key==='skill')h.skillPower*=1.2;if(o.key==='heal')h.hp=Math.min(h.maxHp,h.hp+55);h.down=false;h.hp=Math.max(h.maxHp*.35,h.hp);this.ready[slot]=true;if(this.ready.every(Boolean)){this.mode='complete';this.emit('complete');}}
 nextRoom(){if(this.mode!=='complete')return;this.room++;this.wave=1;this.mode='play';this.clearBuffers();for(const h of this.heroes){h.hp=Math.min(h.maxHp,h.hp+25);h.action=null;h.invuln=1;}this.spawnWave();}
 snapshot(){return{mode:this.mode,reason:this.reason,coordinateSystem:'ground center (0,0), x right, y down, screen y scaled 0.707',time:+this.time.toFixed(3),room:this.room,wave:this.wave,level:this.level,kills:this.kills,heroes:this.heroes.map(h=>({id:h.id,role:h.role,ai:h.ai,x:+h.x.toFixed(2),y:+h.y.toFixed(2),hp:+h.hp.toFixed(1),maxHp:h.maxHp,down:h.down,revive:+h.revive.toFixed(2),face:h.face,action:h.action?.type||'idle',actionTime:h.action?.t,invuln:h.invuln,cooldowns:[...h.cd,h.dodgeCd],power:h.power,damageDone:h.damageDone})),enemies:this.enemies.map(e=>({id:e.id,kind:e.kind,x:+e.x.toFixed(1),y:+e.y.toFixed(1),hp:+e.hp.toFixed(1),attack:e.action?{x:e.action.x,y:e.action.y,r:e.action.r,t:e.action.t,windup:e.action.windup}:null})),projectiles:this.projectiles.length,ready:this.ready,selection:this.selection,offers:this.offers,obstacles:this.obstacles,camera:this.camera};}
}


