"""Build lossless runtime WebP derivatives; never overwrite authored PNGs.

Run with Python + Pillow. Shop thumbnails alone are cropped/resized to 384px,
enough for the largest 128px detail view at 3x DPR. All other images retain
their exact resolution and visible RGBA pixels.
"""
from pathlib import Path
from PIL import Image, ImageChops
import hashlib
import io
import json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets/runtime'
OUT.mkdir(exist_ok=True)
read = lambda p: json.loads((ROOT / p).read_text(encoding='utf-8-sig'))
paths = set()
for role in ['warrior', 'mage', 'archer']:
    paths.add('assets/characters/' + read(f'assets/characters/{role}.json')['image'])
for item in read('assets/portraits/manifest.json').values():
    paths.add(item['src'])
world = read('assets/world/manifest.json')
paths.add('assets/world/' + world['background'])
paths.update('assets/world/' + x['file'] for x in world['pages'].values())
equipment = read('assets/equipment/manifest.json')
paths.update('assets/equipment/' + x['image'] for x in [*equipment['bodies'].values(), *equipment['weapons'].values()])
paths.update('assets/adventure/' + x['file'] for x in read('assets/adventure/manifest.json')['assets'].values())
for group, names in {
    'builds': ['aegis', 'bloodspin', 'inferno', 'icelance', 'markedshot', 'shadow', 'coldfield'],
    'universal': ['seedling', 'dustling', 'gnat', 'spiritdog', 'paperbird', 'thornpet'],
    'frontend': ['title-cute', 'loading-goblin'],
}.items():
    paths.update(f'assets/{group}/{name}.png' for name in names)
shop = read('assets/shop/manifest.json')
paths.add('assets/shop/' + shop['bonus']['file'])
mapping, records = {}, []

def export(source, thumbnail=None):
    image = Image.open(ROOT / source).convert('RGBA')
    if thumbnail:
        x, y, w, h = thumbnail
        image = image.crop((x, y, x+w, y+h))
        image.thumbnail((384, 384), Image.Resampling.LANCZOS)
    data = io.BytesIO()
    image.save(data, 'WEBP', lossless=True, method=6, exact=True)
    encoded = data.getvalue()
    decoded = Image.open(io.BytesIO(encoded)).convert('RGBA')
    # Transparent RGB is irrelevant to compositing; verify every visible pixel
    # against black and white backgrounds, including alpha and soft edges.
    assert decoded.size == image.size
    assert image.getchannel('A').tobytes() == decoded.getchannel('A').tobytes()
    for color in [(0, 0, 0, 255), (255, 255, 255, 255)]:
        bg = Image.new('RGBA', image.size, color)
        assert ImageChops.difference(Image.alpha_composite(bg, image), Image.alpha_composite(bg, decoded)).convert('RGB').getbbox() is None
    digest = hashlib.sha256(encoded).hexdigest()[:12]
    filename = source.removeprefix('assets/').replace('/', '-').removesuffix('.png') + '-' + digest + '.webp'
    (OUT / filename).write_bytes(encoded)
    target = 'assets/runtime/' + filename
    records.append({'source': source, 'target': target, 'sourceBytes': (ROOT/source).stat().st_size, 'bytes': len(encoded), 'width': image.width, 'height': image.height, 'thumbnail': bool(thumbnail)})
    return target, image.size

for source in sorted(paths):
    mapping[source] = export(source)[0]
for item in shop['icons'].values():
    target, size = export('assets/shop/' + item['file'], item['frame'])
    item['file'] = '../runtime/' + Path(target).name
    item['frame'] = [0, 0, *size]
(OUT / 'shop-manifest.json').write_text(json.dumps(shop, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
(ROOT / 'src/coop/runtime-art-files.js').write_text('// Generated by tools/optimize-runtime-art.py. Authored PNGs remain untouched.\nexport const RUNTIME_ART_FILES = Object.freeze(' + json.dumps(mapping, indent=2) + ');\n', encoding='utf-8')
(OUT / 'build-report.json').write_text(json.dumps(records, indent=2) + '\n', encoding='utf-8')
# Static HTML/CSS URLs must match preloads exactly to avoid duplicate downloads.
for relative in ['index.html', 'src/coop/start-screen.css']:
    p = ROOT / relative
    text = p.read_text(encoding='utf-8')
    import re
    for name in ['title-cute', 'loading-goblin']:
        target = mapping[f'assets/frontend/{name}.png']
        text = re.sub(r'assets/(?:frontend/' + name + r'\.png|runtime/frontend-' + name + r'-[a-f0-9]+\.webp)', target, text)
    p.write_text(text, encoding='utf-8')
print(json.dumps({'images': len(records), 'before': sum(x['sourceBytes'] for x in records), 'after': sum(x['bytes'] for x in records)}))
