import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'file:///C:/Users/fuweicheng/.codex/skills/node_modules/playwright/index.mjs';
const out='output/v07/browser';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:940}}),errors=[],failed=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
const state=()=>page.evaluate(()=>JSON.parse(render_game_to_text()));
const advance=ms=>page.evaluate(ms=>advanceTime(ms),ms);
const tap=async key=>{await page.keyboard.down(key);await advance(16);await page.keyboard.up(key);await advance(16);};
const shot=async name=>{await page.evaluate(()=>coopTest.render());await page.locator('#game canvas').screenshot({path:`${out}/${name}.png`});};
const mark=s=>{checks.push(s);console.log('PASS',s);};
async function arena(){await page.evaluate(async()=>{coopTest.start(['warrior','mage'],2);const w=coopTest.world;const {addFixtureCompanions}=await import('/tests/hero-fixture.mjs');addFixtureCompanions(w);w.pressure=null;w.enemies=[];w.obstacles=[];w.effects=[];w.waveDuration=999;w.options.shake=false;w.time=10;w.heroes.forEach((h,i)=>{h.ai=i===2;h.attackCd=999;h.x=(i-1)*160;h.y=0;h.skills=[2,2];});w.camera={x:0,y:0,zoom:.8};coopTest.router.flush();});}
try{
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:4173/');await page.waitForFunction(()=>window.assetsReady,null,{timeout:60000});await advance(0);
 assert.equal((await state()).universalArt.loaded,6);await tap('Enter');assert.equal((await state()).enemies.length,(await state()).pressure.initial);await advance(4500);await shot('continuous-horde');mark('six new PNG atlases load; fresh empty-skill adventure shows continuous crowd');
 await arena();await page.evaluate(()=>{const w=coopTest.world,h=w.heroes[0];w.random=()=>0;const e=w.createEnemy('seedling',h.x+120,0);w.enemies=[e];w.damageEnemy(e,999,h);});let s=await state();assert.equal(s.xp,0);assert.ok(s.pickups.some(p=>p.type==='xp'));await shot('ground-loot');
 await page.keyboard.down('d');await advance(650);await page.keyboard.up('d');s=await state();assert.ok(s.xp>0&&s.gold>0);mark('real movement attracts XP and gold; killing alone grants no experience');
 await arena();await page.evaluate(()=>{const w=coopTest.world;w.heroes[0].passives={needleMagazine:1,mineShoes:1,orbitBlades:1,kineticWheel:1};w.beginReward('skill');w.offers[0]=[{key:'passive:refractLens',kind:'passive',icon:'refract',title:'折射镜片 I',desc:'通用飞针命中后折射一名近敌'}];});await tap('e');s=await state();assert.equal(s.offers[0].length,4);assert.equal(s.rewardMenus[0].type,'replace');await shot('two-player-replacement');await tap('e');assert.equal((await state()).ready[0],false);await shot('replacement-source-warning');await tap('r');assert.equal((await state()).rewardMenus[0],null);await tap('e');await tap('s');await tap('e');assert.equal((await state()).heroes[0].passives.refractLens,1);assert.equal((await state()).ready[1],false);await tap('Enter');assert.equal((await state()).mode,'play');mark('keyboard players select independently; four-slot replacement rejects lost source and supports cancel');
 await arena();await page.evaluate(async()=>{const w=coopTest.world;const {universalDeath,universalCast,universalDodge,universalHurt}=await import('/src/coop/universal-combat.js');w.random=()=>0;const h=w.heroes[0],m=w.heroes[1],a=w.heroes[2];h.passives={boneWhistle:2,paperCrow:2,needleMagazine:2,orbitBlades:2};m.passives={guard:2,shieldBrood:2,mineShoes:2,scavengeSigil:2};m.awakening='thornFortress';a.passives={needleMagazine:2,returnCore:2,magnetAstrolabe:2,echoPosts:1};a.awakening='starMagazine';
 for(let i=0;i<24;i++){const e=w.createEnemy(['seedling','dustling','gnat'][i%3],-250+(i%8)*85,100+Math.floor(i/8)*80);e.hp=e.maxHp=500;e.cd=99;e.freeze=99;w.enemies.push(e);}
 const e=w.enemies[0];for(let i=0;i<4;i++){w.time+=.5;w.damageEnemy(e,1,h,0,'attack',0,null,{eventId:w.nextAttackId++});w.damageEnemy(e,1,a,0,'attack',0,null,{eventId:w.nextAttackId++});}w.damageEnemy(e,999,h);w.request(h,'skill1',{x:1,y:0});m.shield=60;w.damageHero(m,25,{x:m.x+40,y:m.y});
 w.universalObjects.push({kind:'mine',owner:1,x:-90,y:-120,life:5,max:6,arm:0,r:64,damage:20},{kind:'sigil',owner:1,x:120,y:90,life:4,max:5,arm:0,r:70,damage:15},{kind:'post',owner:2,x:210,y:-150,life:10,max:12,r:12},{kind:'post',owner:2,x:340,y:70,life:10,max:12,r:12,link:{x:210,y:-150}});coopTest.render();});await advance(120);await shot('universal-combat');s=await state();assert.ok(s.pets.some(p=>p.kind==='dog'));assert.ok(s.pets.some(p=>p.kind==='turret'));assert.ok(s.universalObjects.length>0);assert.ok(s.heroes[2].universal.ammo>0);mark('pets, thorn turret, independent needles, orbit blades and traps render as different battlefield objects');
 await arena();await page.evaluate(()=>{const w=coopTest.world;w.room=10;w.bossRoom=true;w.clears=18;w.heroes[0].core='bulwark';w.heroes[1].core='pyromancer';w.heroes[2].ai=true;w.beginReward('skill');});await shot('boss-route');await tap('s');await tap('e');s=await state();assert.equal(s.offers[0].length,2);assert.equal(s.rewardMenus[0].type,'reshape');await shot('core-reshape');await tap('e');await tap('Enter');assert.equal((await state()).mode,'upgrade');await tap('Enter');assert.equal((await state()).mode,'shop');await page.evaluate(()=>{coopTest.world.leaveShop(0);coopTest.world.leaveShop(1);});assert.equal((await state()).mode,'complete');mark('Boss route precedes reveal; two-choice reshape and partner high reward finish separately');
 await arena();await page.evaluate(()=>{const w=coopTest.world;w.room=14;w.mode='complete';});await shot('elite-challenge');await page.evaluate(()=>coopTest.world.toggleChallenge());assert.equal(await page.evaluate(()=>coopTest.world.challengeNext),true);await tap('Enter');assert.equal((await state()).eliteChallenge,true);mark('optional mid-late elite challenge activates real pressure modifier');
 await page.evaluate(()=>{const w=coopTest.world;w.pressure=null;w.enemies=[];w.room=20;w.wave=1;w.bossRoom=true;w.waveDuration=0;w.waveTimer=2;});await advance(20);assert.equal((await state()).mode,'shop');await page.evaluate(()=>{coopTest.world.leaveShop(0);coopTest.world.leaveShop(1);});assert.equal((await state()).mode,'victory');await shot('standard-victory');await tap('Enter');s=await state();assert.equal(s.endless,true);assert.equal(s.room,21);mark('standard run ends at room20 and entering endless preserves the party');
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync(`${out}/results.json`,JSON.stringify({checks,errors,failed,scope:'Browser controls, renderer and staged real World mechanics. Fixture builds and monster health are explicit for visual capture; not a natural-run balance test.'},null,2));
}finally{await browser.close();}
