import {chromium} from 'file:///C:/Users/fuweicheng/.codex/skills/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const out='output/coop-verification';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1440,height:940}});const errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));
const state=()=>p.evaluate(()=>JSON.parse(render_game_to_text()));
const advance=ms=>p.evaluate(ms=>advanceTime(ms),ms);
const tap=async(key,ms=35)=>{await p.keyboard.down(key);await advance(ms);await p.keyboard.up(key);await advance(20);};
const shot=async(name)=>{await p.evaluate(()=>coopTest.render());await p.screenshot({path:`${out}/${name}.png`});};
const mark=(s)=>{checks.push(s);console.log('PASS',s);};
try{
 await p.goto('http://127.0.0.1:4173/');await p.waitForFunction(()=>window.assetsReady);await advance(0);assert.equal((await state()).mode,'menu');await shot('menu');mark('menu renders and assets ready');
 await tap('Enter');assert.equal((await state()).mode,'play');mark('Enter starts selected distinct roles');
 const before=await state();await p.keyboard.down('d');await p.keyboard.down('ArrowDown');await advance(400);await p.keyboard.up('d');await p.keyboard.up('ArrowDown');await advance(20);const after=await state();assert.ok(after.heroes[0].x>before.heroes[0].x+55);assert.ok(after.heroes[1].y>before.heroes[1].y+50);mark('two simultaneous keyboard players move independently');
 await p.evaluate(()=>{coopTest.world.heroes.forEach(h=>h.skills=[1,1]);});await tap('q');assert.ok((await state()).heroes[0].cooldowns[0]>0);await tap('Numpad2');assert.ok((await state()).heroes[1].cooldowns[1]>0);await advance(120);await tap('Space',80);assert.equal((await state()).heroes[0].action,'dodge');await shot('combat');mark('P1 shield charge and dodge, P2 frost skill');
 await tap('p');assert.equal((await state()).mode,'paused');const frozen=(await state()).time;await advance(1000);assert.equal((await state()).time,frozen);await shot('pause');await tap('p');assert.equal((await state()).mode,'play');mark('pause freezes simulation and resumes');
 await p.evaluate(()=>{coopTest.world.beginUpgrade();coopTest.router.flush();});await advance(20);await tap('s');assert.equal((await state()).selection[0],1);await tap('e');assert.deepEqual((await state()).ready,[true,false,true]);await tap('ArrowDown');assert.equal((await state()).selection[1],1);await shot('upgrade');await tap('Enter');assert.equal((await state()).mode,'play');await p.evaluate(()=>{coopTest.world.wave=2;coopTest.world.beginReward('skill');coopTest.router.flush();});await tap('e');await tap('Enter');assert.equal((await state()).mode,'complete');await shot('complete');await tap('Enter');assert.equal((await state()).room,2);assert.equal((await state()).mode,'play');mark('independent selection, waiting player can still operate, both ready then next room');
 await p.evaluate(()=>{coopTest.start(['archer','warrior']);coopTest.world.heroes.forEach(h=>h.skills=[1,1]);});await advance(20);await tap('q');await tap('e');assert.equal((await state()).heroes[2].role,'mage');assert.ok((await state()).heroes[0].cooldowns[0]>0);await shot('archer');mark('alternative roles assign remaining role to AI');
 await p.evaluate(()=>{const r=coopTest.router;r.bind(0,{type:'gamepad',id:0});r.bind(1,{type:'gamepad',id:1});const pad=(index,axes=[0,0],pressed=[])=>({index,axes,mapping:'standard',buttons:Array.from({length:17},(_,i)=>({pressed:pressed.includes(i)}))});window.fakePad=pad;coopTest.setPads([pad(0),pad(1)]);});await advance(20);const padBefore=await state();await p.evaluate(()=>coopTest.setPads([fakePad(0,[.8,0],[0]),fakePad(1,[0,1],[2])]));await advance(110);const padAfter=await state();assert.equal(padAfter.heroes[0].action,'dodge');assert.ok(padAfter.heroes[1].cooldowns[0]>0);assert.ok(padAfter.heroes[0].x>padBefore.heroes[0].x);await shot('dual-pad');mark('two simulated gamepads route independent movement and skills');
 await p.evaluate(()=>coopTest.setPads([fakePad(0)]));await advance(40);assert.equal((await state()).mode,'paused');assert.equal((await state()).devices[1].type,'disconnected');await p.evaluate(()=>coopTest.setPads([fakePad(0),fakePad(1)]));await advance(40);assert.equal((await state()).devices[1].type,'disconnected');await shot('disconnect');await p.evaluate(()=>{coopTest.router.claim(1);coopTest.setPads([fakePad(0),fakePad(1,[0,0],[0])]);});await advance(20);assert.equal((await state()).devices[1].type,'gamepad');mark('disconnect pauses, reconnect does not steal slot, explicit rebind works');
 await p.evaluate(()=>{coopTest.router.bind(0,{type:'keyboard',id:0});coopTest.router.bind(1,{type:'keyboard',id:1});coopTest.setPads([]);coopTest.start();coopTest.world.heroes.forEach(h=>{h.down=true;h.hp=0;});});await advance(20);assert.equal((await state()).mode,'defeat');await shot('defeat');await tap('Enter');assert.equal((await state()).mode,'play');mark('team defeat and restart');
 await p.evaluate(()=>{window.dispatchEvent(new Event('blur'));});assert.equal((await state()).mode,'paused');mark('focus loss clears input and pauses');await tap('p');
 await p.locator('#fullscreen').click();await p.waitForFunction(()=>!!document.fullscreenElement);await p.keyboard.press('Escape');mark('fullscreen opens and exits');
 // End-to-end combat: no health/damage/kill overrides; two input bots dodge and use abilities.
 const run=await p.evaluate(()=>{coopTest.start();const w=coopTest.world;for(let i=0;i<60*300&&!['complete','defeat'].includes(w.mode);i++){if(w.mode==='upgrade'){w.confirm(0);w.confirm(1);}else{const inputs=w.heroes.slice(0,2).map(h=>w.aiInput(h));w.advance(1/60,inputs);}}coopTest.render();return w.snapshot();});fs.writeFileSync(`${out}/room-result.json`,JSON.stringify(run,null,2));assert.equal(run.mode,'complete');assert.equal(run.kills,76);await shot('room-cleared');mark('whole room clears through real combat, 76 enemy kills across 8 timed batches, no health or damage overrides');
 assert.equal(errors.length,0);fs.writeFileSync(`${out}/results.json`,JSON.stringify({checks,errors,hardware:'Gamepads simulated. No physical controller tested.'},null,2));
}finally{await b.close();}

