import {chromium} from 'file:///C:/Users/fuweicheng/.codex/skills/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=(process.env.CODEX_BASE_URL||'http://127.0.0.1:4173').replace(/\/$/,''),out=process.env.CODEX_VERIFY_OUT||'output/verification/codex';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:980}}),checks=[],errors=[],resourceFailures=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>resourceFailures.push({url:r.url(),failure:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)resourceFailures.push({url:r.url(),status:r.status()});});
const mark=label=>{checks.push(label);console.log('PASS',label);},state=()=>page.evaluate(()=>JSON.parse(render_game_to_text())),advance=ms=>page.evaluate(ms=>advanceTime(ms),ms),shot=name=>page.screenshot({path:`${out}/${name}.png`});
const pad=(buttons=[],axes=[0,0])=>({index:0,mapping:'standard',axes,buttons:Array.from({length:17},(_,i)=>({pressed:buttons.includes(i),value:+buttons.includes(i)}))});
const setPad=async buttons=>{await page.evaluate(p=>coopTest.setPads([p]),pad(buttons));await advance(25);};
const padTap=async buttons=>{await setPad(buttons);await setPad([]);};
const worldState=()=>page.evaluate(()=>coopTest.world.snapshot());
const close=async()=>{await page.keyboard.press('Escape');await page.waitForFunction(()=>!coopTest.codex.isOpen);await page.waitForTimeout(30);};
const open=async()=>{await page.keyboard.press('i');await page.waitForFunction(()=>coopTest.codex.isOpen);};
const start=async()=>{await page.evaluate(()=>{coopTest.setPads([]);coopTest.router.bind(0,{type:'keyboard',id:0});coopTest.router.bind(1,{type:'keyboard',id:1});coopTest.start(['warrior','mage'],1);});await advance(1);};
try{
 await page.goto(`${base}/codex.html`);await page.waitForFunction(()=>window.assetsReady===true);let s=await state();assert.equal(s.page,'codex');assert.equal(s.artReady,true);assert.equal(s.artFailed,false);assert.ok(s.count>36);await shot('standalone-desktop');mark('standalone catalogue loads data and original artwork');
 const art=await page.locator('.codex-preview').evaluate(c=>{const p=c.getContext('2d').getImageData(0,0,c.width,c.height).data,set=new Set();for(let i=0;i<p.length;i+=16)if(p[i+3])set.add(`${p[i]},${p[i+1]},${p[i+2]}`);return{colors:set.size,width:c.width,height:c.height};});assert.ok(art.colors>100,'preview must contain rendered illustration pixels');
 await page.locator('[data-role="mage"]').click();s=await state();assert.equal(s.role,'mage');assert.ok(s.count>0);await page.locator('.codex-kind select').selectOption('active');s=await state();assert.equal(s.kind,'active');assert.equal(s.count,2);mark('role and type filters select the two mage active skills');
 await page.locator('.codex-search input').fill('不存在的条目_zzxyz');assert.equal((await state()).count,0);assert.equal(await page.locator('.codex-empty').count(),1);await shot('empty-filter');await page.locator('.codex-reset').click();assert.ok((await state()).count>36);mark('query empty result and reset preserve usable navigation');
 for(const category of ['equipment','monsters','skills']){await page.locator(`[data-category="${category}"]`).click();assert.equal((await state()).category,category);assert.ok((await state()).count>0);}mark('all three catalogue categories have records');
 await page.locator('.codex-card').first().click();const selected=(await state()).selectedId;assert.equal(decodeURIComponent(new URL(page.url()).hash.slice(1)),selected);assert.ok(await page.locator('.codex-related-link').count()>0);await page.locator('.codex-related-link').first().click();const related=(await state()).selectedId;assert.notEqual(related,selected);await page.reload();await page.waitForFunction(()=>window.assetsReady===true);assert.equal((await state()).selectedId,related);mark('related entry links update deep hash and survive reload');
 await page.setViewportSize({width:390,height:844});await page.locator('.codex-back').click();assert.equal((await state()).detail,false);await page.locator('.codex-card').first().click();assert.equal((await state()).detail,true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('standalone-mobile-detail');await page.locator('.codex-back').click();assert.equal((await state()).detail,false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('standalone-mobile-list');mark('390px mobile list/detail/back has no horizontal overflow');
 await page.setViewportSize({width:1440,height:980});await page.goto(`${base}/`);await page.waitForFunction(()=>window.assetsReady===true);await start();await open();await page.waitForFunction(()=>coopTest.codex.snapshot().artReady);const frozen=await worldState();assert.equal(frozen.mode,'paused');
 await page.locator('.codex-search input').fill('');await page.keyboard.type('wasdqerf ');await page.keyboard.press('Space');await advance(2000);assert.deepEqual(await worldState(),frozen);assert.equal(await page.evaluate(()=>!!document.fullscreenElement),false);await shot('ingame-paused-search');await close();assert.equal((await state()).mode,'play');assert.equal((await worldState()).time,frozen.time);await advance(100);assert.ok((await worldState()).time>frozen.time);mark('I pauses combat; typing gameplay keys cannot move/cast/fullscreen; Escape resumes unchanged time');
 for(const mode of ['upgrade','shop']){
  await start();await page.evaluate(mode=>{const w=coopTest.world;if(mode==='upgrade')w.beginReward('skill');else{w.room=5;w.wave=2;w.clears=10;w.mode='complete';w.enterShop();}},mode);const before=await worldState();await open();await page.keyboard.type('qer');await advance(500);await close();assert.deepEqual(await worldState(),before);mark(`codex preserves ${mode} offers, cursors, readiness and wallet`);
 }
 await start();await page.locator('#fullscreen').click();await page.waitForFunction(()=>!!document.fullscreenElement);const fullBefore=await worldState();await open();assert.equal(await page.locator('.codex-dialog').isVisible(),true);await advance(500);await shot('fullscreen-codex');await close();assert.equal((await worldState()).time,fullBefore.time);assert.ok(['play','paused'].includes((await state()).mode));assert.equal((await state()).room,fullBefore.room);if(await page.evaluate(()=>!!document.fullscreenElement))await page.evaluate(()=>document.exitFullscreen());mark('fullscreen catalogue remains visible; Escape closes without changing gameplay or rewards');
 await start();await page.evaluate(()=>coopTest.world.pause('原先已暂停'));await open();await close();s=await state();assert.equal(s.mode,'paused');assert.equal(s.reason,'原先已暂停');mark('closing the catalogue preserves a pre-existing pause');
 await start();await open();await page.evaluate(()=>dispatchEvent(new Event('blur')));await close();s=await state();assert.equal(s.mode,'paused');assert.match(s.reason,/失去焦点/);mark('focus loss during catalogue requires explicit later resume');
 await start();await page.evaluate(()=>coopTest.router.bind(0,{type:'gamepad',id:0}));await setPad([]);await padTap([8]);assert.equal((await state()).codex.open,true);await page.locator('.codex-reset').click();const padFrozen=await worldState(),old=await state();await padTap([13]);assert.notEqual((await state()).codex.selectedId,old.codex.selectedId);await padTap([15]);assert.notEqual((await state()).codex.category,old.codex.category);await padTap([0]);assert.equal((await state()).codex.detail,true);await page.evaluate(p=>coopTest.setPads([p]),pad([0,2,3],[1,1]));await advance(1000);assert.deepEqual(await worldState(),padFrozen);await setPad([]);await shot('ingame-gamepad-details');await padTap([9]);await page.waitForFunction(()=>!coopTest.codex.isOpen);await page.waitForTimeout(30);assert.equal((await state()).mode,'play');mark('View opens; D-pad down/right and A browse; Start closes without gameplay input leakage');
 await setPad([]);await padTap([8]);assert.equal((await state()).codex.open,true);await page.evaluate(()=>coopTest.setPads([]));await advance(100);await close();s=await state();assert.equal(s.mode,'paused');assert.equal(s.devices[0].type,'disconnected');assert.match(s.reason,/断开/);mark('controller disconnect during catalogue keeps the world paused');
 await start();await page.evaluate(()=>coopTest.router.bind(0,{type:'gamepad',id:0}));await setPad([]);await padTap([8]);assert.equal((await state()).codex.open,true);await padTap([8]);await page.waitForFunction(()=>!coopTest.codex.isOpen);await page.waitForTimeout(30);assert.equal((await state()).mode,'play');mark('View button toggles open and close on separate edges');
 assert.deepEqual(errors,[]);assert.deepEqual(resourceFailures,[]);mark('no console/page errors or failed HTTP/art resources');
}catch(error){await shot('failure').catch(()=>{});throw error;}finally{fs.writeFileSync(`${out}/browser.json`,JSON.stringify({base,checks,errors,resourceFailures},null,2)+'\n');await browser.close();}
